= Logging

All warning and error messages in Asciidoctor.js are routed through a logger.
Many of the messages also include context about the source location (file, dir, path, lineno), which can be useful for integrations and tooling.

When using the API, you can feed your own logger to the `LoggerManager` to capture, route, or observe the messages.

== Default Logger

The default logger will output all warning and error messages to `stderr` (the standard error output stream).

Depending on your JavaScript environment, `stderr` will be resolved to:

* https://developer.mozilla.org/fr/docs/Web/API/Console/warn[`console.warn`] function in a browser environment
* https://nodejs.org/api/process.html#process_process_stderr[`process.stderr`] property in a Node.js environment
* `print` function in a Nashorn environment

== In-memory Logger

In addition to the default logger, Asciidoctor.js provides a built-in in-memory logger named `MemoryLogger`.
This logger can be use to capture messages.

First we need to instantiate this logger using the `$new()` function:

```js
const memoryLogger = asciidoctor.MemoryLogger.$new();
```

Once the logger is instantiated we can replace the default logger with the in-memory logger:

```js
asciidoctor.LoggerManager.setLogger(memoryLogger);
```

[NOTE]
====
If you want to restore the default logger, you should save a reference before replacing it:

```js
const loggerManager = asciidoctor.LoggerManager;
const defaultLogger = loggerManager.getLogger(); // <1>
try {
  const memoryLogger = asciidoctor.MemoryLogger.$new();
  loggerManager.setLogger(memoryLogger); // <2>
  // do something with the in-memory logger
} finally {
  loggerManager.setLogger(defaultLogger); // <3>
}
```
<1> save the default logger
<2> replace the default logger with the in-memory logger
<3> restore the default logger
====

=== Error and warning messages

The in-memory logger stores every warning and error messages generated by the Asciidoctor.js processor.
Once the processing is done, you can retrieve all these messages using the `getMessages` function:


```js
const loggerManager = asciidoctor.LoggerManager;
const memoryLogger = asciidoctor.MemoryLogger.$new();
loggerManager.setLogger(memoryLogger);

asciidoctor.convert('input');

memoryLogger.getMessages(); // returns an array of Message
```

For every message, you can get the following information:

```js
const message = memoryLogger.getMessages()[0];
console.log(message.getSeverity()); // <1>
console.log(message.getText()); // <2>
const sourceLocation = message.getSourceLocation(); // <3>
if (sourceLocation) {
  console.log(sourceLocation.getLineNumber()); // <4>
  console.log(sourceLocation.getFile()); // <5>
  console.log(sourceLocation.getDirectory()); // <6>
  console.log(sourceLocation.getPath()); // <7>
}
```
<1> returns the severity (`ERROR` or `WARNING`)
<2> returns the error or warning text message
<3> returns the context about the source location (can be undefined)
<4> returns the source line number associated to the message
<5> returns the file associated to the message (can be undefined)
<6> returns the directory associated to the message
<7> returns the path associated to the message (or `<stdin>`)
