version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: "⬆️"
- package-ecosystem: npm
  directory: "/packages/core"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/packages/asciidoctor"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: "⬆️"
