= Contributing
:uri-org: https://github.com/asciidoctor
:uri-repo: {uri-org}/asciidoctor.js
:uri-issues: {uri-repo}/issues
:uri-rel-file-base: link:
:uri-contribute-code: {uri-rel-file-base}CONTRIBUTING-CODE.adoc

We want you!
Yes, _you_.

*Anyone* can contribute to an Asciidoctor project.
If you have a specialty, or just some creativity to share, we need your participation.
We have big aspirations for the project and we need an assortment of skill sets in order to reach them.
Make no mistake, contributing is _not_ just for developers.

Of course, we'll always need help with the code as it's the basis of the project.
But code isn't going to make the project successful alone.
We also need documentation, automation, design, marketing, communication, advocacy and more for it to make an impact.

Here are just a few of the ways you can contribute to the project:

* Join our thriving Asciidoctor community at https://asciidoctor.zulipchat.com/ where you can:
** Share your feedback
** Educate with your knowledge and techniques on a subject
** Tell us about your great idea!
* Reporting bugs (_The easiest way to get started!_)
* Suggesting new feature or improvements in the issue tracker
* Speaking about the technology
* Advocating for the technology
* Assisting with design and/or UX (stylesheets, themes, logos, etc)
* Conducting user studies and collecting feedback
* Automating system administration tasks (releases, changelog, announcements, hosting, etc)
* Writing, editing or maintaining the documentation
* Organizing the content (information architecture & content strategy)
* Using or extending the software in a creative way
* Testing a prerelease, a pull request or main
* Reviewing or providing feedback on pull requests
* Writing code (_No patch is too small!_)
** Fixing typos
** Adding or revising comments or API docs
** Fixing issues
** Writing tests
** Refactoring the code
* Something we haven't suggested...seriously!

The best way to get involved is just to show up and express your interest.
We have a very friendly and encouraging culture.
Harassment or offensive behavior is simply not tolerated.
We are positive, even when being critical.
We also strive to lift others up and help them be successful.
We want your choice to participate in an Asciidoctor project be the start of an exciting and rewarding journey.
So thanks for showing up!

---

If you want to write code, the {uri-contribute-code}[Contributing Code] guide will help you to get started quickly.
