= Asciidoctor.js User Manual

== API

=== How to convert an AsciiDoc content

[source,javascript]
----
const asciidoctor = require('asciidoctor.js')();
const content = 'Hello, _Asciidoctor_';
const html = asciidoctor.convert(content);
console.log(html);
// <div class="paragraph">
// <p>Hello, <em>Asciidoctor</em></p>
// </div>
----

=== How to use conversion options

[source,javascript]
----
const asciidoctor = require('asciidoctor.js')();
const content = '= Document title';
const html = asciidoctor.convert(content, {safe: 'safe', attributes: {showtitle: true, icons: 'fonts'}});
console.log(html);
// <h1>Document title</h1>
----

=== How to parse a file into an Asciidoctor Document object

[source,javascript]
----
const asciidoctor = require('asciidoctor.js')();
const doc = asciidoctor.loadFile('sample.adoc');
console.log(doc.getAuthor());
----

=== How to configure the runtime environment

NOTE: By default, Asciidoctor.js will try his best to automatically detect the runtime environment.

If you want to explicitly define the runtime environment, you can use a `runtime` configuration object when instantiating Asciidoctor.js: 

[source,javascript]
----
const asciidoctor = require('asciidoctor.js')({ 
  runtime: {
    platform: 'browser', 
    engine: 'v8', 
    framework: 'webextensions'
  }
});
----

=== How to configure the I/O module

NOTE: By default, Asciidoctor.js will determine the I/O module upon the runtime environment.

If you want to explicitly define the I/O module, you can specify the attribute `runtime.ioModule` when instantiating Asciidoctor.js: 

[source,javascript]
----
const asciidoctor = require('asciidoctor.js')({
  runtime: {
    ioModule: 'xmlhttprequest'
  }
});
----

`ioModule` can be one of:

* `spidermonkey`
* `phantomjs`
* `node`
* `java_nio`
* `xmlhttprequest`

=== How to convert a list of AsciiDoc files contained within a folder (using Node.js)

[source,javascript]
----
const glob = require('glob');
const asciidoctor = require('asciidoctor.js')();

glob('documentation/*.adoc', function (err, files) { // <1>
  files.forEach(function(file) {
    asciidoctor.convertFile(file); // <2>
  });
});
----
<1> We are using `glob` module to iterate through every .adoc file inside the directory
<2> Convert each file using the `convertFile` method

=== How to set document attribute

You can set document attributes after loading AsciiDoc content.

[source,javascript]
----
const content = '== Title';
const doc = asciidoctor.load(content);
console.log(doc.getAttribute('data-uri')); // prints undefined
console.log(doc.getAttribute('data-uri', 'false')); // prints 'false'

doc.setAttribute('data-uri', 'true');
console.log(doc.getAttribute('data-uri')); // prints 'true'
----

=== How to unset/delete document attribute

You can unset document attributes after loading AsciiDoc content.

[source,javascript]
----
const content = '== Title';
const doc = asciidoctor.load(content);
doc.setAttribute('data-uri', 'true');
console.log(doc.getAttribute('data-uri')); // prints 'true'

doc.removeAttribute('data-uri');
console.log(doc.getAttribute('data-uri')); // prints undefined
----

=== How to register an extension ?

You can register an extension globally as follows:

[source,javascript]
----
const asciidoctor = require('asciidoctor.js')();
asciidoctor.Extensions.register(function () {
  this.block(function () {
    const self = this;
    self.named('shout');
    self.onContext('paragraph');
    self.process(function (parent, reader) {
      const lines = reader.getLines().map(function (l) { return l.toUpperCase(); });
      return self.createBlock(parent, 'paragraph', lines);
    });
  });
});

const text = `[shout]\
\nSay it loud.\
\nSay it proud.`;

const html = asciidoctor.convert(text);
console.log(html);

// <div class="paragraph">
// <p>SAY IT LOUD.
// SAY IT PROUD.</p>
// </div>
----

You can also create one or more registries.
It can be useful when you want to convert the same text with different extensions enabled.

[source,javascript]
----
const asciidoctor = require('asciidoctor.js')();

const registryA = asciidoctor.Extensions.create();
const registryB = asciidoctor.Extensions.create();

registryA.block(function () {
  const self = this;
  self.named('shout');
  self.onContext('paragraph');
  self.process(function (parent, reader) {
    // Transform text to uppercase
    const lines = reader.getLines().map(function (l) { return l.toUpperCase(); });
    return self.createBlock(parent, 'paragraph', lines);
  });
});

registryB.block(function () {
  const self = this;
  self.named('shout');
  self.onContext('paragraph');
  self.process(function (parent, reader) {
    // Replace period at end of line with three three exclamation marks
    const lines = reader.getLines().map(function (l) { return l.replace(/\.$/g, ' !!!'); });
    return self.createBlock(parent, 'paragraph', lines);
  });
});

const text = `[shout]\
\nSay it loud.\
\nSay it proud.`;

console.log(asciidoctor.convert(text, {'extension_registry': registryA}));
console.log('');
console.log(asciidoctor.convert(text, {'extension_registry': registryB}));

// <div class="paragraph">
// <p>SAY IT LOUD.
// SAY IT PROUD.</p>
// </div>
//
// <div class="paragraph">
// <p>Say it loud !!!
// Say it proud !!!</p>
// </div>
----

In the example above, we've created two registries:

* `registryA`
* `registryB`

Both registry have a `[shout]` block extension registered with a specific implementation.

The first block extension is registered in the `registryA` and will transform the text to uppercase. 
The other one is registered in the `registryB` and will replace `.` by `{nbsp}!!!`.
