// ESM conversion of sections_test.rb — context 'Ids'

import { test, describe } from 'node:test'
import assert from 'node:assert/strict'

import { Compliance } from '../src/compliance.js'
import { assertXpath, assertMessage, usingMemoryLogger } from './helpers.js'
import { documentFromString, blockFromString } from './harness.js'

// ── Sections › Ids ────────────────────────────────────────────────────────────

describe('Sections', () => {
  describe('Ids', () => {
    test('synthetic id is generated by default', async () => {
      const sec = await blockFromString('== Section One')
      assert.equal(sec.id, '_section_one')
    })

    test('duplicate synthetic id is automatically enumerated', async () => {
      const doc = await documentFromString('== Section One\n\n== Section One')
      assert.equal(doc.blocks.length, 2)
      assert.equal(doc.blocks[0].id, '_section_one')
      assert.equal(doc.blocks[1].id, '_section_one_2')
    })

    test('synthetic id removes non-word characters', async () => {
      const sec = await blockFromString("== We\u2019re back!")
      assert.equal(sec.id, '_were_back')
    })

    test('synthetic id removes repeating separators', async () => {
      const sec = await blockFromString('== Section $ One')
      assert.equal(sec.id, '_section_one')
    })

    test('synthetic id removes entities', async () => {
      const sec = await blockFromString('== Ben & Jerry &amp; Company&sup1; &#34;Ice Cream Brothers&#34; &#12354;')
      assert.equal(sec.id, '_ben_jerry_company_ice_cream_brothers')
    })

    test('synthetic id removes adjacent entities with mixed case', async () => {
      const sec = await blockFromString('== a &#xae;&AMP;&#xA9; b')
      assert.equal(sec.id, '_a_b')
    })

    test('synthetic id removes XML tags', async () => {
      const sec = await blockFromString('== Use the `run` command to make it icon:gear[]')
      assert.equal(sec.id, '_use_the_run_command_to_make_it_gear')
    })

    test('synthetic id collapses repeating spaces', async () => {
      const sec = await blockFromString('== Go    Far')
      assert.equal(sec.id, '_go_far')
    })

    test('synthetic id replaces hyphens with separator', async () => {
      const sec = await blockFromString('== State-of-the-art design')
      assert.equal(sec.id, '_state_of_the_art_design')
    })

    test('synthetic id replaces dots with separator', async () => {
      const sec = await blockFromString('== Section 1.1.1')
      assert.equal(sec.id, '_section_1_1_1')
    })

    test('synthetic id prefix can be customized', async () => {
      const sec = await blockFromString(':idprefix: id_\n\n== Section One')
      assert.equal(sec.id, 'id_section_one')
    })

    test('synthetic id prefix can be set to blank', async () => {
      const sec = await blockFromString(':idprefix:\n\n== Section One')
      assert.equal(sec.id, 'section_one')
    })

    test('synthetic id prefix is stripped from beginning of id if set to blank', async () => {
      const sec = await blockFromString(':idprefix:\n\n== & ! More')
      assert.equal(sec.id, 'more')
    })

    test('synthetic id separator can be customized', async () => {
      const sec = await blockFromString(':idseparator: -\n\n== Section One')
      assert.equal(sec.id, '_section-one')
    })

    test('synthetic id separator can be hyphen and hyphens are preserved', async () => {
      const sec = await blockFromString(':idseparator: -\n\n== State-of-the-art design')
      assert.equal(sec.id, '_state-of-the-art-design')
    })

    test('synthetic id separator can be dot and dots are preserved', async () => {
      const sec = await blockFromString(':idseparator: .\n\n== Version 5.0.1')
      assert.equal(sec.id, '_version.5.0.1')
    })

    test('synthetic id separator can only be one character', async () => {
      const input = ':idseparator: -=-\n\n== This Section Is All You Need'
      const sec = await blockFromString(input)
      assert.equal(sec.id, '_this-section-is-all-you-need')
    })

    test('synthetic id separator can be set to blank', async () => {
      const sec = await blockFromString(':idseparator:\n\n== Section One')
      assert.equal(sec.id, '_sectionone')
    })

    test('synthetic id separator can be set to blank when idprefix is blank', async () => {
      const sec = await blockFromString(':idprefix:\n:idseparator:\n\n== Section One')
      assert.equal(sec.id, 'sectionone')
    })

    test('synthetic id separator is removed from beginning of id when idprefix is blank', async () => {
      const sec = await blockFromString(':idprefix:\n:idseparator: _\n\n== +Section One')
      assert.equal(sec.id, 'section_one')
    })

    test('synthetic ids can be disabled', async () => {
      const sec = await blockFromString(':sectids!:\n\n== Section One\n')
      assert.equal(sec.id, null)
    })

    test('explicit id in anchor above section title overrides synthetic id', async () => {
      const sec = await blockFromString('[[one]]\n== Section One')
      assert.equal(sec.id, 'one')
    })

    test('explicit id in block attributes above section title overrides synthetic id', async () => {
      const sec = await blockFromString('[id=one]\n== Section One')
      assert.equal(sec.id, 'one')
    })

    test('empty id in block attributes above section title prevents assignment of synthetic id', async () => {
      const sect = await blockFromString('[id=]\n== Section One')
      assert.equal(sect.id, null)
    })

    test('explicit id set using shorthand in style above section title overrides synthetic id', async () => {
      const sec = await blockFromString('[#one]\n== Section One')
      assert.equal(sec.id, 'one')
    })

    test('should use explicit id from last block attribute line above section title that defines an explicit id', async () => {
      const input = '[#un]\n[#one]\n== Section One'
      const sec = await blockFromString(input)
      assert.equal(sec.id, 'one')
    })

    test('explicit id can be defined using an embedded anchor', async () => {
      const sec = await blockFromString('== Section One [[one]] ==')
      assert.equal(sec.id, 'one')
      assert.equal(sec.title, 'Section One')
    })

    test('explicit id can be defined using an embedded anchor when using setext section titles', async () => {
      const input = 'Section Title [[refid,reftext]]\n-------------------------------'
      const sec = await blockFromString(input)
      assert.equal(sec.title, 'Section Title')
      assert.equal(sec.id, 'refid')
      assert.equal(sec.getAttribute('reftext'), 'reftext')
    })

    test('explicit id can be defined using an embedded anchor with reftext', async () => {
      const sec = await blockFromString('== Section One [[one,Section Uno]] ==')
      assert.equal(sec.id, 'one')
      assert.equal(sec.title, 'Section One')
      assert.equal(sec.getAttribute('reftext'), 'Section Uno')
    })

    test('id and reftext in embedded anchor cannot be quoted', async () => {
      const sec = await blockFromString('== Section One [["one","Section Uno"]] ==')
      assert.notEqual(sec.id, 'one')
      assert.equal(sec.title, 'Section One [["one","Section Uno"]]')
      assert.equal(sec.getAttribute('reftext'), null)
    })

    test('reftext in embedded anchor may contain comma', async () => {
      const sec = await blockFromString('== Section One [[one, Section,Uno]] ==')
      assert.equal(sec.id, 'one')
      assert.equal(sec.title, 'Section One')
      assert.equal(sec.getAttribute('reftext'), 'Section,Uno')
    })

    test('should unescape but not process inline anchor', async () => {
      const sec = await blockFromString('== Section One \\[[one]] ==')
      assert.notEqual(sec.id, 'one')
      assert.equal(sec.title, 'Section One [[one]]')
    })

    test('should not process inline anchor in section title if section has explicit ID', async () => {
      const sec = await blockFromString('[#sect-one]\n== Section One [[one]]')
      assert.equal(sec.id, 'sect-one')
      assert.equal(sec.title, 'Section One <a id="one"></a>')
    })

    test('should apply substitutions to title with attribute references when registering section with auto-generated ID', async () => {
      const input = `= Document Title
:foo: bar

See <<_section_baz>>.

:foo: baz

== Section {foo}

That's all, folks!`
      const doc = await documentFromString(input)
      const ref = doc.catalog.refs['_section_baz']
      assert.ok(ref != null)
      const output = await doc.convert({ standalone: false })
      assertXpath(output, '//a[@href="#_section_baz"][text()="Section baz"]', 1)
      assertXpath(output, '//h2[@id="_section_baz"][text()="Section baz"]', 1)
    })

    test('should apply substitutions to title with attribute references when registering section with explicit ID', async () => {
      const input = `= Document Title
:foo: bar

See <<explicit>>.

:foo: baz

[#explicit]
== Section {foo}

That's all, folks!`
      const doc = await documentFromString(input)
      const ref = doc.catalog.refs['explicit']
      assert.ok(ref != null)
      const output = await doc.convert({ standalone: false })
      assertXpath(output, '//a[@href="#explicit"][text()="Section baz"]', 1)
      assertXpath(output, '//h2[@id="explicit"][text()="Section baz"]', 1)
    })

    test('should not apply substitutions to title with attribute references when parsing section with empty ID', async () => {
      const input = `= Document Title
:attribute-missing: warn

[id=]
== Section {missing}

That's all, folks!`
      await usingMemoryLogger(async (logger) => {
        const doc = await documentFromString(input)
        assert.deepEqual(doc.catalog.refs, {})
        assert.equal(logger.messages.length, 0)
      })
    })

    test('title substitutions are applied before generating id', async () => {
      const sec = await blockFromString('== Section{sp}One\n')
      assert.equal(sec.id, '_section_one')
    })

    test('synthetic ids are unique', async () => {
      const input = '== Some section\n\ntext\n\n== Some section\n\ntext'
      const doc = await documentFromString(input)
      assert.equal(doc.blocks[0].id, '_some_section')
      assert.equal(doc.blocks[1].id, '_some_section_2')
    })

    test('can set start index of synthetic ids', async () => {
      const oldStartIndex = Compliance.uniqueIdStartIndex
      try {
        const input = '== Some section\n\ntext\n\n== Some section\n\ntext'
        Compliance.uniqueIdStartIndex = 1
        const doc = await documentFromString(input)
        assert.equal(doc.blocks[0].id, '_some_section')
        assert.equal(doc.blocks[1].id, '_some_section_1')
      } finally {
        Compliance.uniqueIdStartIndex = oldStartIndex
      }
    })

    test('should use specified id and reftext when registering section reference', async () => {
      const input = `[[install,Install Procedure]]
== Install

content`
      const doc = await documentFromString(input)
      const ref = doc.catalog.refs['install']
      assert.ok(ref != null)
      assert.equal(ref.reftext, 'Install Procedure')
      assert.equal(doc.resolveId('Install Procedure'), 'install')
    })

    test('should use specified reftext when registering section reference', async () => {
      const input = `[reftext="Install Procedure"]
== Install

content`
      const doc = await documentFromString(input)
      const ref = doc.catalog.refs['_install']
      assert.ok(ref != null)
      assert.equal(ref.reftext, 'Install Procedure')
      assert.equal(doc.resolveId('Install Procedure'), '_install')
    })

    test('should resolve attribute reference in title using attribute defined at location of section title', async () => {
      const input = `:platform-id: linux
:platform-name: Linux

[#install-{platform-id}]
== Install on {platform-name}

content

:platform-id: win32
:platform-name: Windows

[#install-{platform-id}]
== Install on {platform-name}

content`
      const doc = await documentFromString(input)
      const ref = doc.catalog.refs['install-win32']
      assert.ok(ref != null)
      assert.equal(ref.title, 'Install on Windows')
      assert.equal(doc.resolveId('Install on Windows'), 'install-win32')
    })

    test('should substitute attributes when registering reftext for section', async () => {
      const input = `:platform-name: n/a
== Overview

:platform-name: Linux

[[install,install on {platform-name}]]
== Install

content`
      const doc = await documentFromString(input)
      const ref = doc.catalog.refs['install']
      assert.ok(ref != null)
      assert.equal(ref.reftext, 'install on Linux')
      assert.equal(doc.resolveId('install on Linux'), 'install')
    })

    test('duplicate section id should not overwrite existing section id entry in references table', async () => {
      const input = `[#install]
== First Install

content

[#install]
== Second Install

content`
      await usingMemoryLogger(async (logger) => {
        const doc = await documentFromString(input)
        const ref = doc.catalog.refs['install']
        assert.ok(ref != null)
        assert.equal(ref.reftext, null)
        assert.equal(ref.title, 'First Install')
        assert.equal(doc.resolveId('First Install'), 'install')
        assertMessage(logger, 'WARN', '<stdin>: line 7: id assigned to section already in use: install')
      })
    })

    test('should warn if explicit section ID matches auto-generated section ID', async () => {
      const input = `== Do Not Repeat Yourself

content

[#_do_not_repeat_yourself]
== Do Not Repeat Yourself

content`
      await usingMemoryLogger(async (logger) => {
        const doc = await documentFromString(input)
        const ref = doc.catalog.refs['_do_not_repeat_yourself']
        assert.ok(ref != null)
        assert.equal(ref.reftext, null)
        assert.equal(ref.title, 'Do Not Repeat Yourself')
        assert.equal(doc.resolveId('Do Not Repeat Yourself'), '_do_not_repeat_yourself')
        assertMessage(logger, 'WARN', '<stdin>: line 6: id assigned to section already in use: _do_not_repeat_yourself')
        const converted = await doc.convert({ standalone: false })
        assert.equal((converted.match(/id="_do_not_repeat_yourself"/g) || []).length, 2)
      })
    })

    test('duplicate block id should not overwrite existing section id entry in references table', async () => {
      const input = `[#install]
== First Install

content

[#install]
content`
      await usingMemoryLogger(async (logger) => {
        const doc = await documentFromString(input)
        const ref = doc.catalog.refs['install']
        assert.ok(ref != null)
        assert.equal(ref.reftext, null)
        assert.equal(ref.title, 'First Install')
        assert.equal(doc.resolveId('First Install'), 'install')
        assertMessage(logger, 'WARN', '<stdin>: line 7: id assigned to block already in use: install')
      })
    })
  })
})
