export class AbstractBlock extends AbstractNode {
    contentModel: string;
    blocks: any[];
    subs: any[];
    numeral: any;
    style: any;
    defaultSubs: any;
    sourceLocation: any;
    level: number;
    _nextSectionIndex: number;
    _nextSectionOrdinal: number;
    isBlock(): boolean;
    isInline(): boolean;
    set title(val: any);
    get title(): any;
    precomputeTitle(): Promise<void>;
    _computingTitle: boolean;
    get rawTitle(): any;
    get attrSubstitutedTitle(): any;
    hasTitle(): boolean;
    set caption(val: any);
    get caption(): any;
    get file(): any;
    get lineno(): any;
    setContext(context: any): void;
    set number(val: any);
    get number(): any;
    convert(): Promise<any>;
    render(): Promise<any>;
    content(): Promise<string>;
    getContent(): Promise<string>;
    append(block: any): this;
    hasBlocks(): boolean;
    hasSections(): boolean;
    sections(): any[];
    alt(): any;
    getAlt(): any;
    captionedTitle(): string;
    listMarkerKeyword(listType?: any): any;
    hasSub(name: any): boolean;
    removeSub(name: any): void;
    xreftext(xrefstyle?: any): Promise<any>;
    assignCaption(value?: any, captionContext?: any): void;
    assignNumeral(section: any): void;
    reindexSections(): void;
    findBy(selector?: {}, filter?: any): any[];
    query(selector?: {}, filter?: any): any[];
    nextAdjacentBlock(): any;
    getContext(): any;
    getBlocks(): any[];
    getSections(): any[];
    getTitle(): any;
    setTitle(val: any): void;
    getCaption(): any;
    setCaption(val: any): void;
    getCaptionedTitle(): string;
    getStyle(): any;
    setStyle(val: any): void;
    getLevel(): number;
    setLevel(val: any): void;
    getLineNumber(): any;
    getSourceLocation(): any;
    getSubstitutions(): any[];
    hasSubstitution(name: any): boolean;
    addSubstitution(name: any): void;
    removeSubstitution(name: any): void;
    #private;
}
import { AbstractNode } from './abstract_node.js';
