export class ImageReference {
    constructor(target: any, imagesdir: any);
    target: any;
    imagesdir: any;
    toString(): any;
}
export class Footnote {
    constructor(index: any, id: any, text: any);
    index: any;
    id: any;
    text: any;
}
export class AttributeEntry {
    constructor(name: any, value: any, negate?: any);
    name: any;
    value: any;
    negate: any;
    saveTo(blockAttributes: any): this;
}
export class DocumentTitle {
    constructor(val: any, opts?: {});
    _sanitized: boolean;
    main: any;
    subtitle: any;
    combined: any;
    get title(): any;
    isSanitized(): boolean;
    hasSubtitle(): boolean;
    toString(): any;
}
export class Author {
    constructor(name: any, firstname: any, middlename: any, lastname: any, initials: any, email: any);
    name: any;
    firstname: any;
    middlename: any;
    lastname: any;
    initials: any;
    email: any;
}
export class Document extends AbstractBlock<string> {
    static create(data: any, options?: {}): Promise<Document>;
    constructor(data?: any, options?: {});
    set converter(v: any);
    get converter(): any;
    _converter: any;
    parent: this;
    document: this;
    parentDocument: any;
    catalog: any;
    _attributeOverrides: any;
    safe: any;
    compatMode: any;
    outfilesuffix: any;
    sourcemap: any;
    _timings: any;
    pathResolver: any;
    extensions: any;
    syntaxHighlighter: any;
    _initializeExtensions: boolean;
    _parentDoctype: any;
    _inputMtime: any;
    _parsed: boolean;
    _reftexts: {};
    header: Section;
    _headerAttributes: any;
    _counters: {};
    _attributesModified: Set<any>;
    _docinfoProcessorExtensions: {};
    options: Readonly<{}>;
    baseDir: any;
    _maxAttributeValueSize: number;
    backend: any;
    doctype: any;
    reader: any;
    get references(): any;
    nested(): boolean;
    parse(data?: any): Promise<Document>;
    isParsed(): boolean;
    counter(name: any, seed?: any): any;
    incrementAndStoreCounter(counterName: any, block: any): any;
    counterIncrement(counterName: any, block: any): any;
    register(type: any, value: any): boolean | Inline;
    resolveId(text: any): any;
    _buildReftextsMap(): Promise<void>;
    isMultipart(): boolean;
    hasFootnotes(): boolean;
    get footnotes(): any;
    get callouts(): any;
    isNested(): boolean;
    isEmbedded(): boolean;
    hasExtensions(): boolean;
    source(): any;
    sourceLines(): any;
    basebackend(base: any): boolean;
    set title(val: any);
    get title(): any;
    doctitle(opts?: {}): any;
    get name(): any;
    xreftext(_xrefstyle?: any): any;
    get author(): any;
    get revdate(): any;
    authors(): Author[];
    isNotitle(): boolean;
    isNoheader(): boolean;
    isNofooter(): boolean;
    firstSection(): any;
    hasHeader(): boolean;
    append(block: any): this;
    finalizeHeader(unrootedAttributes: any, headerValid?: boolean): any;
    playbackAttributes(blockAttributes: any): void;
    _restoreAttributes(): void;
    setAttribute(name: any, value?: string, skipSubs?: boolean): string;
    deleteAttribute(name: any): boolean;
    isAttributeLocked(name: any): boolean;
    attributeLocked(name: any): boolean;
    setHeaderAttribute(name: any, value?: string, overwrite?: boolean): boolean;
    _convertAsciiDocCells(block?: this): Promise<void>;
    convert(opts?: {}): any;
    render(opts?: {}): any;
    write(output: any, target: any): Promise<void>;
    docinfo(location?: string, suffix?: any): Promise<string>;
    _docinfoProcessors(location: any): boolean;
    getTitle(): any;
    setTitle(val: any): void;
    getDoctitle(opts?: {}): any;
    getDocumentTitle(opts?: {}): any;
    getDoctype(): any;
    getBackend(): any;
    getSafe(): any;
    getCompatMode(): any;
    getSourcemap(): any;
    setSourcemap(val: any): void;
    getOutfilesuffix(): any;
    getOptions(): Readonly<{}>;
    getSource(): any;
    getSourceLines(): any;
    getReader(): any;
    getFootnotes(): any;
    getCallouts(): any;
    getCatalog(): any;
    getCounters(): {};
    getAuthor(): any;
    getExtensions(): any;
    getParentDocument(): any;
    getParent(): any;
    removeAttribute(name: any): any;
    _applyAttributeValueSubs(value: any): any;
    _applyAttributeEntryValueSubs(value: any): Promise<any>;
    _resolveDocinfoSubs(): any;
    _resolveAllTexts(block: any): Promise<void>;
    _createConverter(backend: any, delegateBackend: any): any;
    _clearPlaybackAttributes(attributes: any): void;
    _saveAttributes(): void;
    _fillDatetimeAttributes(attrs: any, inputMtime: any): void;
    _updateBackendAttributes(newBackend: any, init?: boolean): any;
    _updateDoctypeAttributes(newDoctype: any): any;
}
export namespace Document {
    export { Footnote };
}
export const _deps: {};
import { AbstractBlock } from './abstract_block.js';
import { Section } from './section.js';
import { Inline } from './inline.js';
