export class Cursor {
    constructor(file: any, dir?: any, path?: any, lineno?: number);
    file: any;
    dir: any;
    path: any;
    lineno: number;
    advance(num: any): void;
    get lineInfo(): string;
    toString(): string;
    getLineNumber(): number;
    getFile(): any;
    getDirectory(): any;
    getPath(): any;
}
export class Reader {
    constructor(data?: any, cursor?: any, opts?: {});
    file: any;
    _dir: any;
    path: any;
    lineno: any;
    _document: any;
    sourceLines: any;
    _lines: any;
    _mark: any;
    _lookAhead: number;
    processLines: boolean;
    _unescapeNextLine: boolean;
    unterminated: any;
    _saved: any;
    hasMoreLines(): boolean;
    empty(): boolean;
    eof(): boolean;
    nextLineEmpty(): Promise<boolean>;
    isNextLineEmpty(): Promise<boolean>;
    peekLine(direct?: boolean): Promise<any>;
    peekLines(num?: any, direct?: boolean): Promise<any[]>;
    readLine(): Promise<any>;
    readLines(): Promise<any[]>;
    readlines(): Promise<any[]>;
    read(): Promise<string>;
    advance(): Promise<boolean>;
    unshiftLine(lineToRestore: any): void;
    restoreLine(lineToRestore: any): void;
    unshiftLines(linesToRestore: any): void;
    restoreLines(linesToRestore: any): void;
    replaceNextLine(replacement: any): boolean;
    replaceLine(replacement: any): boolean;
    skipBlankLines(): Promise<number>;
    skipCommentLines(): Promise<void>;
    skipLineComments(): Promise<any[]>;
    terminate(): void;
    readLinesUntil(options?: {}, filter?: any): Promise<any[]>;
    get cursor(): Cursor;
    cursorAtLine(lineno: any): Cursor;
    cursorAtMark(): Cursor;
    cursorBeforeMark(): Cursor;
    cursorAtPrevLine(): Cursor;
    mark(): void;
    lineInfo(): string;
    get lines(): any;
    string(): any;
    source(): any;
    save(): void;
    restoreSave(): void;
    discardSave(): void;
    toString(): string;
    _shift(): any;
    _unshift(line: any): void;
    _unshiftAll(linesToRestore: any): void;
    processLine(line: any): any;
    _prepareLines(data: any, opts?: {}): any;
    getCursor(): Cursor;
    getLines(): any;
    getString(): any;
    getLogger(): any;
    createLogMessage(text: any, context?: {}): any;
    get logger(): any;
    _logWarn(msg: any, { sourceLocation, includeLocation }?: {}): void;
    _logError(msg: any, opts?: {}): void;
    _logInfo(msg: any, { sourceLocation }?: {}): void;
}
export class PreprocessorReader extends Reader {
    constructor(document: any, data?: any, cursor?: any, opts?: {});
    _sourcemap: any;
    _maxdepth: {
        abs: number;
        curr: number;
        rel: number;
    };
    includeStack: any[];
    _includes: any;
    _skipping: boolean;
    _conditionalStack: any[];
    _includeProcessorExtensions: any;
    hasMoreLines(): Promise<boolean>;
    empty(): Promise<boolean>;
    eof(): Promise<boolean>;
    peekLine(direct?: boolean): any;
    pushInclude(data: any, file?: any, path?: any, lineno?: number, attributes?: {}): this;
    get includeDepth(): number;
    exceedsMaxDepth(): number;
    exceededMaxDepth(): number;
    hasIncludeProcessors(): boolean;
    createIncludeCursor(file: any, path: any, lineno: any): Cursor;
    processLine(line: any): Promise<any>;
    _preprocessConditionalDirective(name: any, target: any, delimiter: any, text: any): boolean;
    _preprocessIncludeDirective(target: any, attrlist: any): Promise<any>;
    _isBrowserMode(): any;
    _resolveIncludePath(target: any, attrlist: any, attributes: any): Promise<any>;
    _popInclude(): void;
    _filterLinesByLinenos(fileLines: any, incLinenos: any): {
        incLines: string[];
        incOffset: number;
    };
    _filterLinesByTags(fileLines: any, incPath: any, expandedTarget: any, targetType: any, incTagsIn: any, parsedAttrs: any): {
        incLines: string[];
        incOffset: number;
    };
    _skipFrontMatter(data: any, incrementLinenos?: boolean): any[];
    _resolveExprVal(val: any): any;
    _evalOp(lhs: any, op: any, rhs: any): boolean;
    _splitDelimitedValue(val: any): any;
}
