export const CC_ALL: "[\\s\\S]";
export const CC_ANY: ".";
export const CC_EOL: "$";
export const CC_ALPHA: "\\p{Alphabetic}";
export const CG_ALPHA: "\\p{Alphabetic}";
export const CC_ALNUM: "\\p{Alphabetic}\\p{N}";
export const CG_ALNUM: "[\\p{Alphabetic}\\p{N}]";
export const CC_WORD: "\\p{Alphabetic}\\p{N}\\p{Pc}";
export const CG_WORD: "[\\p{Alphabetic}\\p{N}\\p{Pc}]";
export const CG_BLANK: "[\\p{Zs}\\t]";
export const QuoteAttributeListRxt: "\\[([^\\[\\]]+)\\]";
export const AuthorInfoLineRx: RegExp;
export const AuthorDelimiterRx: RegExp;
export const RevisionInfoLineRx: RegExp;
export const ManpageTitleVolnumRx: RegExp;
export const ManpageNamePurposeRx: RegExp;
export const ConditionalDirectiveRx: RegExp;
export const EvalExpressionRx: RegExp;
export const IncludeDirectiveRx: RegExp;
export const TagDirectiveRx: RegExp;
export const AttributeEntryRx: RegExp;
export const InvalidAttributeNameCharsRx: RegExp;
export const AttributeEntryPassMacroRx: RegExp;
export const AttributeReferenceRx: RegExp;
export const BlockAnchorRx: RegExp;
export const BlockAttributeListRx: RegExp;
export const BlockAttributeLineRx: RegExp;
export const BlockTitleRx: RegExp;
export const AdmonitionParagraphRx: RegExp;
export const LiteralParagraphRx: RegExp;
export const AtxSectionTitleRx: RegExp;
export const ExtAtxSectionTitleRx: RegExp;
export const SetextSectionTitleRx: RegExp;
export const InlineSectionAnchorRx: RegExp;
export const InvalidSectionIdCharsRx: RegExp;
export const SectionLevelStyleRx: RegExp;
export const AnyListRx: RegExp;
export const UnorderedListRx: RegExp;
export const OrderedListRx: RegExp;
export namespace OrderedListMarkerRxMap {
    let arabic: RegExp;
    let loweralpha: RegExp;
    let lowerroman: RegExp;
    let upperalpha: RegExp;
    let upperroman: RegExp;
}
export const DescriptionListRx: RegExp;
export const DescriptionListSiblingRx: {
    '::': RegExp;
    ':::': RegExp;
    '::::': RegExp;
    ';;': RegExp;
};
export const CalloutListRx: RegExp;
export const CalloutExtractRx: RegExp;
export const CalloutExtractRxt: "(\\\\)?<()([\\d]+|\\.)>(?=(?: ?\\\\?<(?:\\d+|\\.)>)*$)";
export const CalloutExtractRxMap: any;
export const CalloutScanRx: RegExp;
export const CalloutSourceRx: RegExp;
export const CalloutSourceRxt: "(\\\\)?&lt;()([\\d]+|\\.)&gt;(?=(?: ?\\\\?&lt;(?:\\d+|\\.)&gt;)*$)";
export const CalloutSourceRxMap: any;
export namespace ListRxMap {
    export { UnorderedListRx as ulist };
    export { OrderedListRx as olist };
    export { DescriptionListRx as dlist };
    export { CalloutListRx as colist };
}
export const ColumnSpecRx: RegExp;
export const CellSpecStartRx: RegExp;
export const CellSpecEndRx: RegExp;
export const CustomBlockMacroRx: RegExp;
export const BlockMediaMacroRx: RegExp;
export const BlockTocMacroRx: RegExp;
export const InlineAnchorRx: RegExp;
export const InlineAnchorScanRx: RegExp;
export const LeadingInlineAnchorRx: RegExp;
export const InlineBiblioAnchorRx: RegExp;
export const InlineEmailRx: RegExp;
export const InlineFootnoteMacroRx: RegExp;
export const InlineImageMacroRx: RegExp;
export const InlineIndextermMacroRx: RegExp;
export const InlineKbdBtnMacroRx: RegExp;
export const InlineLinkRx: RegExp;
export const InlineLinkMacroRx: RegExp;
export const MacroNameRx: RegExp;
export const InlineStemMacroRx: RegExp;
export const InlineMenuMacroRx: RegExp;
export const InlineMenuRx: RegExp;
export namespace InlinePassRx {
    let _false: (string | RegExp)[];
    export { _false as false };
    let _true: (string | RegExp)[];
    export { _true as true };
}
export const InlinePassMacroRx: RegExp;
export const InlineXrefMacroRx: RegExp;
export const HardLineBreakRx: RegExp;
export const MarkdownThematicBreakRx: RegExp;
export const ExtLayoutBreakRx: RegExp;
export const BlankLineRx: RegExp;
export const EscapedSpaceRx: RegExp;
export const ReplaceableTextRx: RegExp;
export const SpaceDelimiterRx: RegExp;
export const SubModifierSniffRx: RegExp;
export const TrailingDigitsRx: RegExp;
export const UriSniffRx: RegExp;
export const XmlSanitizeRx: RegExp;
