= CLI Options

== Security settings

*-B, --base-dir*=_DIR_::
  Base directory containing the document and resources.
  Defaults to the directory containing the source file, or the working directory if the source is read from a stream.
  Can be used as a way to chroot the execution of the program.

*-S, --safe-mode*=_SAFE_MODE_::
  Set xref:asciidoctor::safe-modes.adoc[safe mode] level: _unsafe_, _safe_, _server_ or _secure_.
  Disables potentially dangerous macros in source files, such as `include::[]`.
  If not set, the safe mode level defaults to _unsafe_ when Asciidoctor is invoked using this script.

== Document settings

*-a, --attribute*=_ATTRIBUTE_::
  Define, override or delete a document attribute.
  Command-line attributes take precedence over attributes defined in the source file.
+
_ATTRIBUTE_ is normally formatted as a key-value pair, in the form _NAME=VALUE_.
Alternate acceptable forms are _NAME_ (where the _VALUE_ defaults to an empty string), _NAME!_ (unassigns the _NAME_ attribute) and _NAME=VALUE@_ (where _VALUE_ does not override value of _NAME_ attribute if it's already defined in the source document).
Values containing spaces should be enclosed in quotes.
+
This option may be specified more than once.

*-b, --backend*=_BACKEND_::
  Backend output file format: _html5_, _docbook5_, and _manpage_ are supported out of the box.
  You can also use the backend alias names _html_ (aliased to _html5_) or _docbook_ (aliased to _docbook5_).
  Defaults to _html5_.
  Other options can be passed, but if Asciidoctor cannot find the backend, it will fail during conversion.

*-d, --doctype*=_DOCTYPE_::
  Document type: _article_, _book_, _manpage_ or _inline_.
  Sets the root element when using the _docbook_ backend and the style class on the HTML body element when using the _html_ backend.
  The _book_ document type allows multiple level-0 section titles in a single document.
  The _manpage_ document type enables parsing of metadata necessary to produce a manpage.
  The _inline_ document type allows the content of a single paragraph to be formatted and returned without wrapping it in a containing element.
  Defaults to _article_.

== Document Conversion

*-D, --destination-dir*=_DIR_::
  Destination output directory.
  Defaults to the directory containing the source file, or the working directory if the source is read from a stream.
  If specified, the directory is resolved relative to the working directory.

*-e, --embedded*::
  Output an embeddable document, which excludes the header, the footer, and everything outside the body of the document.
  This option is useful for producing documents that can be inserted into an external template.

*-n, --section-numbers*::
  Auto-number section titles.
  Synonym for *--attribute numbered*.

*-o, --out-file*=_OUT_FILE_::
  Write output to file _OUT_FILE_.
  Defaults to the base name of the input file suffixed with _backend_ extension.
  If the input is read from standard input, then the output file defaults to stdout.
  If _OUT_FILE_ is _-_ then the standard output is also used.
  If specified, the file is resolved relative to the working directory.

*-r, --require*=_LIBRARY_::
  Require the specified library before executing the processor, using the standard Node `require`.
  This option may be specified more than once.

*-s, --no-header-footer*::
  Output an embeddable document, which excludes the header, the footer, and everything outside the body of the document.
  This option is useful for producing documents that can be inserted into an external template.

*-T, --template-dir*=_DIR_::
A directory containing custom converter templates that override one or more templates from the built-in set.
Asciidoctor.js supports EJS (`.ejs`), Handlebars (`.handlebars`, `.hbs`), Nunjucks (`.nunjucks`, `.njk`), Pug (`.pug`) and Template Literals (`.js`).
+
[NOTE]
====
Please note that the dependencies are optional, so you will need to install them explicitly.
For instance, if you want to use Nunjucks, you will need to install the nunjucks package:

 $ npm i nunjucks
====
+
This option may be specified more than once.
Matching templates found in subsequent directories override ones previously discovered.
+
Learn more about the xref:extend:converter/template-converter.adoc[Template Converter].

== Processing information

*-q, --quiet*::
  Silence warnings.

*--trace*::
  Include backtrace information on errors.
  Not enabled by default.

*-v, --verbose*::
  Verbosely print processing information and configuration file checks to `stderr`.

*-t, --timings*::
  Display timings information (time to read, parse and convert).

== Program information

*-h, --help*::
  Show the help message.

*-V, --version*::
  Print program version number. A lowercase `-v` can be used if no other flags or arguments are present.