blank_issues_enabled: false
contact_links:
  - name: Asciidoctor Community Support
    url: https://chat.asciidoctor.org
    about: Please ask questions about how to use Asciidoctor.js or the AsciiDoc syntax here.
