= Include directive support matrix
:icon-ok: 👌
:icon-ko: ❌
ifdef::env-github[]
:icon-ok: :ok_hand:
:icon-ko: :x:
endif::[]

This document describes how the include directive is resolved in the following environments:

* Browser (XMLHttpRequest IO module)
* Node.js
* MRI (Ruby)

[cols="1m,1m,1,1,1", options="header"]
|===
|Path
|Base dir
|Browser
|Node.js
|MRI

|+path/to/file.adoc+
|+file:///root+
|{icon-ok}
|{icon-ok}
|{icon-ko} +
The resolved path is `/root/file:/root/path/to/file.adoc`.

|+path/../path/to/file.adoc+
|+file:///root+
|{icon-ok}
|{icon-ok}
|{icon-ko} +
The resolved path is `/root/file:/root/path/to/file.adoc`.

|+file:///root/path/to/file.adoc+
|
|{icon-ok}
|{icon-ok}
|{icon-ko} +
include uri not readable: `\file:///root/path/to/file.adoc`.

|+file:///root/path/../path/to/file.adoc+
|
|{icon-ok}
|{icon-ok}
|{icon-ko} +
include uri not readable: `\file:///root/path/../path/to/file.adoc`.

|+path/to/file.adoc+
|
|{icon-ko} +
Unable to get the current directory in a reliable way.
|{icon-ok}
|{icon-ok}

|+file:///root/path/to/file.adoc+
|+file:///root/path/to+
|{icon-ok}
|{icon-ok}
|{icon-ko} +
include uri not readable: `\file:///root/path/to/file.adoc`.

|+https://raw.com/master/file.adoc+
|+https://raw.com/master+
|{icon-ok}
|{icon-ok}
|{icon-ok}

|+https://raw.com/master/file.adoc+
|
|{icon-ok}
|{icon-ok}
|{icon-ok}

|+file.adoc+
|+https://raw.com/master+
|{icon-ok}
|{icon-ko} +
`SecurityError: Jail is not an absolute path: \https://raw.com/master`
|{icon-ko} +
include file not found: `\{local_pwd}/https:/raw.com/master/file.adoc`.

|+../v1.5.0/file.adoc+
|+https://raw.com/master+
|{icon-ok}
|{icon-ko} +
`SecurityError: Jail is not an absolute path: \https://raw.com/master`
|{icon-ko} +
include file not found: `\{local_pwd}/https:/raw.com/master/file.adoc`.

|+https://raw.com/master/../v1.5.0/file.adoc+
|
|{icon-ok}
|{icon-ko} +
The `xmlhttprequest` module does not expand path and therefore returns a 404.
|{icon-ok}
|===
