= Include directive support matrix
:icon-ok: 👌
:icon-ko: ❌
ifdef::env-github[]
:icon-ok: :ok_hand:
:icon-ko: :x:
endif::[]

This document describes how the include directive is resolved in the following environments:

* Browser (XMLHttpRequest IO module)
* Node.js
* MRI (Ruby)

[cols="1m,1m,1,1,1", options="header"]
|===
|Path
|Base dir
|Browser
|Node.js
|MRI

| +path/to/file.adoc+
| +file:///root+
|{icon-ok}
|{icon-ok}
|{icon-ko}
5+a|
MRI: The resolved path is [.path]_/root/file:/root/path/to/file.adoc_.

|+path/../path/to/file.adoc+
|+file:///root+
|{icon-ok}
|{icon-ok}
|{icon-ko}
5+a|
MRI: The resolved path is [.path]_/root/file:/root/path/to/file.adoc_.

|+file:///root/path/to/file.adoc+
|
|{icon-ok}
|{icon-ok}
|{icon-ko}
5+a|
MRI: include uri not readable: [.path]_\file:///root/path/to/file.adoc_.

|+file:///root/path/../path/to/file.adoc+
|
|{icon-ok}
|{icon-ok}
|{icon-ko}
5+a|
MRI: include uri not readable: [.path]_\file:///root/path/../path/to/file.adoc_.

|+path/to/file.adoc+
|
|{icon-ko}
|{icon-ok}
|{icon-ok}
5+a|
Browser: Unable to get the current directory in a reliable way.

|+file:///root/path/to/file.adoc+
|+file:///root/path/to+
|{icon-ok}
|{icon-ok}
|{icon-ko}
5+a|
MRI: include uri not readable: [.path]_\file:///root/path/to/file.adoc_.

|+https://raw.com/master/file.adoc+
|+https://raw.com/master+
|{icon-ok}
|{icon-ok}
|{icon-ok}

|+https://raw.com/master/file.adoc+
|
|{icon-ok}
|{icon-ok}
|{icon-ok}

|+file.adoc+
|+https://raw.com/master+
|{icon-ok}
|{icon-ko}
|{icon-ko}
5+a|
[%hardbreaks]
Node.js: SecurityError: Jail is not an absolute path: [.path]_\https://raw.com/master_
MRI: include file not found: [.path]_\{local_pwd}/https:/raw.com/master/file.adoc_.

|+../v1.5.0/file.adoc+
|+https://raw.com/master+
|{icon-ok}
|{icon-ko}
|{icon-ko}
5+a|
[%hardbreaks]
Node.js: SecurityError: Jail is not an absolute path: [.path]_\https://raw.com/master_
MRI: include file not found: [.path]_\{local_pwd}/https:/raw.com/master/file.adoc_.

|+https://raw.com/master/../v1.5.0/file.adoc+
|
|{icon-ok}
|{icon-ko}
|{icon-ok}
5+a|
Node.js: The xmlhttprequest module does not expand path and therefore returns a 404.
|===
