= Template Converter
:uri-jsapi: http://asciidoctor.github.io/asciidoctor.js/master
:uri-jsapi-abstractnode: {uri-jsapi}/#abstractnode
:uri-jsapi-section: {uri-jsapi}/#section
:uri-jsapi-document: {uri-jsapi}/#document
:uri-jsapi-block: {uri-jsapi}/#block
:uri-handlebars-register-helpers: https://handlebarsjs.com/api-reference/runtime.html#handlebars-registerhelper-name-helper
:uri-handlebars-register-partials: https://handlebarsjs.com/api-reference/runtime.html#handlebars-registerpartial-name-partial
:uri-nunjucks-add-filter: https://mozilla.github.io/nunjucks/api.html#addfilter

On this page, you'll learn how to use templates to have full control over the output.

== Built-in template engines

By default, Asciidoctor.js supports the following template engines with the corresponding file extensions:

EJS::
`.ejs`

Handlebars::
`.handlebars`, `.hbs`

Nunjucks::
`.nunjucks`, `.njk`

Pug::
`.pug`

[NOTE]
====
Please note that the dependencies are optional, so you will need to install them explicitly.
For instance, if you want to use Nunjucks, you will need to install the `nunjucks` package:

 $ npm i nunjucks
====

Once the dependency is installed, you can create template files in a directory.

== Plain JavaScript templates

Asciidoctor.js also supports templates written in plain JavaScript.
In this case, you should write JavaScript files that export a default function:

[source,js]
----
module.exports = ({ node }) => `<p class="paragraph">${node.getContent()}</p>`
----

This function will be called with a <<template-context>> as argument.

== Naming convention

Let's say, we want to use Nunjucks to write templates.
We create a directory named _templates_ and a file named _paragraph.njk_:

[source,njk]
----
<p class="paragraph">{{ node.getContent() | safe }}</p>
----

[NOTE]
====
By default, Nunjucks will automatically escape all output for safety.
Here, we are using the built-in `safe` filter to mark the output as safe.
As a result, Nunjucks will not escape this output.
====

As mentioned above, the file extension _njk_ is important because it tells Asciidoctor.js that this file is a Nunjucks template.
Moreover, the name _paragraph_ is also important as it matches a node name.
For reference, here's the complete list of node's name:

include::partial$node-name-list.adoc[]

You don't need to create a template for all the nodes.
Asciidoctor.js can fallback on a built-in converter.
For instance, we can use the built-in HTML 5 converter for every node except for paragraph nodes where we use a custom template.

== Templates directory

You can instruct Asciidoctor.js to use a template directory from the CLI with the `--template-dir` option (or `-T` for short):

 $ asciidoctor --template-dir ./templates doc.adoc

You can also configure the template directory using the API:

[source,js]
----
asciidoctor.convertFile('doc.adoc', { safe: 'safe', backend: 'html5', template_dir: './templates' })
----

=== Multiple templates directories

It's also possible to use more than one template directory.
In this case, we can repeat the `--template-dir` option from the CLI:

 $ asciidoctor --template-dir ./templates-a --template-dir ./templates-b doc.adoc

In the above command, we are using two templates directories named _templates-a_ and _templates-b_.

From the API, we will need to define the `template_dirs` option:

[source,js]
----
asciidoctor.convertFile('doc.adoc', { safe: 'safe', backend: 'html5', template_dirs: ['./templates-a', './templates-b'] })
----

=== Conflicts resolution

Here's how Asciidoctor.js resolve conflicts in the following situations:

Two or more templates are defined for the same node name in the same directory::
For instance, you have a _paragraph.njk_ and a _paragraph.hbs_ file in your template directory.
In this case, the rule is "last one wins" in alphabetical order.
Since _njk_ is after _hbs_ in alphabetical order, Asciidoctor.js will use the Nunjucks template over the Handlebars template.

Two or more templates are defined for the same node in different directories::
For instance, we have a _paragraph.njk_ in _template-a_ directory and a _paragraph.njk_ in _template-b_ directory.
In this case, the rule is still "last one wins" but the order in the `template_dirs` option is important. +
If I declare the following:
+
[source,js]
----
const options = { template_dirs: ['template-a', 'template-b'] }
----
+
Then _template-b/paragraph.njk_ will win because it's effectively the last one.
Now, if I change the order in the `template_dirs` option:
+
[source,js]
----
const options = { template_dirs: ['template-b', 'template-a'] }
----
+
Then _template-a/paragraph.njk_ will win!

Please note that it's not a recommended practice, and you should try to avoid conflicts upstream.

[[helpers-js-file]]
=== helpers.js file

You can create a `helpers.js` file in your template directory.
This file can be used to declare utility functions that can be used in the templates.
For instance, if you are using Handlebars, you might want to register {uri-handlebars-register-partials}[partials] or {uri-handlebars-register-helpers}[helpers].
Similarly, if you are using Nunjucks, you might want to {uri-nunjucks-add-filter}[add custom filters].

If this file exists, Asciidoctor.js will load it (using the Node.js `require` directive) and call the `configure` function if it's exported:

.helpers.js
[source,js]
----
module.exports.configure = (context) => {
  // ...
}
----

The `context` object will contain an <<isolated-environment,isolated environement>> (if supported) template engine keyed by template engine name:

`handlebars.environment`::
An isolated Handlebars environment obtained via https://handlebarsjs.com/api-reference/runtime.html#handlebars-create[`Handlebars.create()`]

`nunjucks.environment`::
An isolated Nunjucks environment obtained via https://mozilla.github.io/nunjucks/api.html#configure[`nunjucks.configure()`]

Here's a concrete example where we add a Nunjucks filter `shorten` which returns the first count characters in a string, with count defaulting to 5:

.helpers.js
[source,js]
----
module.exports.configure = (context) => {
  context.nunjucks.environment.addFilter('shorten', (str, count) => str.slice(0, count || 5))
}
----

[[isolated-environment]]
==== Isolated environment

An isolated environment means that each environment has its own helpers, partials, filters...
It's worth noting that an environment is isolated per template directory. +
For instance, if we define a value with the same name in two directories the last one won't overwrite the first one:

.web/helpers.js
[source,js]
----
module.exports.configure = (context) => {
  context.nunjucks.environment.addGlobal('cdn', '//cdn.web.com')
}
----

.blog/helpers.js
[source,js]
----
module.exports.configure = (context) => {
  context.nunjucks.environment.addGlobal('cdn', '//cdn.blog.io')
}
----

With the above definition, the value `cdn` will be equals to:

[horizontal]
`//cdn.web.com`:: if we are using the template directory _web_
`//cdn.blog.io`:: if we are using the template directory _blog_

==== Stateless

EJS, Plain JavaScript and Pug templates do not rely on an "environment". +
As a result, you don't need to define a `configure` function.
Instead, you can use the `helpers.js` file to export values and functions that will be accessible in all templates:

.helpers.js
[source,js]
----
let assetUriScheme
module.exports.version = '1.0.0'
module.exports.getAssetUriScheme = (document) => {
  if (assetUriScheme) {
    return assetUriScheme
  }
  const scheme = document.getAttribute('asset-uri-scheme', 'https')
  assetUriScheme = (scheme && scheme.trim() !== '') ? `${scheme}:` : ''
  return assetUriScheme
}
----

In the above example, the value `version` and the function `getAssetUriScheme` will be available on the `helpers` key in the template context:

.video.js
[source,js]
----
module.exports = function ({ node, _, helpers }) {
  const target = node.getAttribute('target')
  const document = node.getDocument()
  const src = `${helpers.getAssetUriScheme(document)}//www.youtube.com/embed/${target}}` // <1>
  return `<figure class="video"><iframe src="${src}" frameborder="0"/></figure>`
}
----
<1> Use the `getAssetUriScheme` function defined in the `helpers.js` file

[[template-context]]
== Template context

Asciidoctor.js will pass the following context to the template:

`node`::
An {uri-jsapi-abstractnode}[AbstractNode] from the Asciidoctor.js AST.
Depending on the context, it can be a {uri-jsapi-section}[Section], a {uri-jsapi-document}[Document], a {uri-jsapi-block}[Block]... +
We recommend reading the {uri-jsapi}[JS API documentation] to find out what it's available on each Node.

`opts`::
An optional JSON of options.

`helpers`::
The functions and values exported from the _helpers.js_ file.
