= Install guide
:url-node-releases: https://nodejs.org/en/about/releases/

On this page, you'll learn:

* [x] How to install Asciidoctor.js.
* [x] How to setup Asciidoctor.js in your JavaScript environment.

== Install Asciidoctor.js

We recommend using the latest long term support (LTS) release of Node.
While you can use other versions of Node, Asciidoctor.js is only tested against {url-node-releases}[active LTS releases].

Once you've installed an active Node LTS release on your machine, open a terminal and type:

[source]
$ npm i asciidoctor

NOTE: If you prefer Yarn over npm, you can install Asciidoctor.js using `yarn add asciidoctor`

Asciidoctor.js provides different builds for different JavaScript environments.
See below for a link to the right one and instructions on how to use it.

== Basic browser setup

Include Asciidoctor.js in a `<script>` tag.
You can instantiate the processor using the `Asciidoctor` global variable.

```html
<script src="node_modules/@asciidoctor/core/dist/browser/asciidoctor.js"></script>
```
```js
var asciidoctor = Asciidoctor()
```

== Node

```js
const Asciidoctor = require('asciidoctor')

const asciidoctor = Asciidoctor()
```

== AMD (System.js, RequireJS, etc)

```js
requirejs(['asciidoctor'], function (asciidoctor) {
  //...
})
```

== TypeScript

```js
import Processor from 'asciidoctor'

const processor = Processor()
```

NOTE: We are using the name `processor` to avoid confusion with the `Asciidoctor` namespace.

== Webpack

```js
import Asciidoctor from 'asciidoctor'

const asciidoctor = Asciidoctor()
```

== GraalVM

=== Node.js application

https://www.graalvm.org/docs/reference-manual/languages/js/[GraalVM can run Node.js applications]. +
To install `asciidoctor.js` module, use the `npm` executable in the [.path]_/bin_ folder of the GraalVM package.

Create the following code snippet to a file named `app.js` and save it in the same directory where you installed the Node.js modules:

.app.js
```js
const Asciidoctor = require('asciidoctor')

const asciidoctor = Asciidoctor()
```

Then execute it on GraalVM using the `node` command (available in the [.path]_/bin_ folder of the GraalVM package):

 $ node app.js

=== Embed in a JVM-based application

https://www.graalvm.org/reference-manual/embed-languages/[With the Graal Polyglot API, you can embed JavaScript code in a JVM-based application].
However, this is currently an *experimental* feature.
Please, share any feedback or issues you may have.

IMPORTANT: The Graal Polyglot feature gives you a "pure" JavaScript (ECMAScript) engine, not a Node.js engine.
In other words, Node.js features such as `require` or core module such as `fs` won't be available.

To embed Asciidoctor.js in a Java application, create the following code snippet to a file named `app.js` (tested on v21.1.0):

.app.js
```js
var asciidoctor = Asciidoctor()
```

Copy the file `node_modules/asciidoctor.js/dist/graalvm/asciidoctor.js` in the resources of your application.
Then create a Java file named `AsciidoctorGraalVM.java` with the following content:

.AsciidoctorGraalVM.java
```java
include::example$AsciidoctorGraalVM.java[]
```
<1> The `IncludeResolver` class will be used to read the content of a file when using the `include::` directive
<2> Make sure that `asciidoctor.js` and `app.js` are available in the classpath of the application

[TIP]
====
The source attribute of the https://github.com/graalvm/graaljs/blob/master/docs/user/JavaScriptCompatibility.md#loadsource[global `load` method] provided by GraalVM can be of type:

- a `String`: the path of the source file or a URL to execute.
- `java.lang.URL`: the URL is queried for the source code to execute.
- `java.io.File`: the File is read for the source code to execute.
====

== What's next?

Now that Asciidoctor.js is installed, you are ready to take a xref:quick-tour.adoc[quick tour].
