= Install guide
:url-node-releases: https://nodejs.org/en/about/releases/

On this page, you'll learn:

* [x] How to install Asciidoctor.js.
* [x] How to setup Asciidoctor.js in your JavaScript environment.

== Install Asciidoctor.js

We recommend using the latest long term support (LTS) release of Node.
While you can use other versions of Node, Asciidoctor.js is only tested against {url-node-releases}[active LTS releases].

Once you've installed an active Node LTS release on your machine, open a terminal and type:

[source]
$ npm i @asciidoctor/core

NOTE: If you prefer Yarn over npm, you can install Asciidoctor.js using `yarn add @asciidoctor/core`

Asciidoctor.js provides different builds for different JavaScript environments.
See below for a link to the right one and instructions on how to use it.

== Basic browser setup

Import Asciidoctor.js in a `<script type="module">` tag.

```html
<script type="module">
  import asciidoctor from './node_modules/@asciidoctor/core/build/browser/index.js'
</script>
```

[NOTE]
====
You need to pay attention to local testing — if you try to load the HTML file locally (i.e. with a file:// URL), you'll run into CORS errors due to JavaScript module security requirements.
You need to do your testing through a server.

Learn more about https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules[JavaScript modules].
====

== Node

[source,js]
----
import asciidoctor from '@asciidoctor/core'
----

[NOTE]
====
`@asciidoctor/core` is also available as a CommonJS (CJS) module:
[source,js]
----
const asciidoctor = require('@asciidoctor/core')
----
====

== What's next?

Now that Asciidoctor.js is installed, you are ready to take a xref:quick-tour.adoc[quick tour].
