data = <<EOS
= AsciiDoc Syntax Quick Reference
Dan Allen; Sarah White
v1.0.3, 2013-08-27
:description: This guide is a quick reference for the common formatting markup and document elements in the AsciiDoc syntax.
:keywords: AsciiDoc, Asciidoctor, syntax, reference, cheatsheet
:imagesdir: ../images
:experimental:
:table-caption!:
:example-caption!:
:figure-caption!:
:idprefix:
:idseparator: -
:linkattrs:
:docref: http://asciidoctor.org/docs
:user-ref: {docref}/user-manual
:fontawesome-ref: http://fortawesome.github.io/Font-Awesome
:icon-inline: {user-ref}/#inline-icons
:icon-attribute: {user-ref}/#size-rotate-and-flip
:video-ref: {user-ref}/#video
:checklist-ref: {user-ref}/#checklists
:list-marker: {user-ref}/#custom-markers
:list-number: {user-ref}/#numbering-styles
:imagesdir-ref: {user-ref}/#imagesdir
:image-attributes: {user-ref}/#put-images-in-their-place
:toc-ref: {user-ref}/#table-of-contents
:para-ref: {user-ref}/#paragraph
:literal-ref: {user-ref}/#literal-text-and-blocks
:admon-ref: {user-ref}/#admonition
:bold-ref: {user-ref}/#bold-and-italic
:quote-ref: {user-ref}/#quotation-marks-and-apostrophes
:sub-ref: {user-ref}/#subscript-and-superscript
:mono-ref: {user-ref}/#monospace
:css-ref: {user-ref}/#custom-styling-with-attributes
:pass-ref: {user-ref}/#passthrough-macros
:mailinglist: http://discuss.asciidoctor.org

////
Syntax to cover:
- preface
- index terms
- built-in attributes (such as {author}, {revision}, etc)
- start=n for ordered lists
- horizontal labeled list
- anchor for any block element
- block metadata (missing example of normal attributes)
- command line reference? perhaps another doc? yes

PDF TODO:
- add license on title page (legalnotice tag)
- table cell bg
- show example of section levels
- syntax highlight ruby code (requires switch to https://code.google.com/p/java-syntax-highlighter)
- style sidebar block
////


AsciiDoc is a mature, lightweight markup language for authoring notes, articles, documentation, books, web pages, slide decks and man pages in plain text.
{description}

[NOTE]
====
Several examples focus on the output generated by the HTML backend.
AsciiDoc produces complementary output when generating DocBook.

Most features labeled ``Asciidoctor only'' can be made available to the native AsciiDoc processor by using https://github.com/asciidoctor/asciidoctor/blob/master/compat/asciidoc.conf[this AsciiDoc configuration file] from the Asciidoctor project.
====

toc::[]

== Paragraphs

.Normal
----
Paragraphs don't require any special markup in AsciiDoc.
A paragraph is just one or more lines of consecutive text.

To begin a new paragraph, separate it by at least one blank line.
----

[.result]
====
Paragraphs don't require any special markup in AsciiDoc.
A paragraph is just one or more lines of consecutive text.

To begin a new paragraph, separate it by at least one blank line.
====

.Line breaks
----
To preserve a line break, end the line in a space followed by a plus sign. +
This results in a visible line break (e.g., +<br>+) between the lines.
----

[.result]
====
To preserve a line break, end the line in a space followed by a plus sign. +
This results in a visible line break (e.g., +<br>+) between the lines.
====

.Literal
----
A normal paragraph.

 A sequence of lines that begin with at least one space is a literal paragraph.
 Literal paragraphs are treated as preformatted text.
 The text is shown in a fixed-width font
 and endlines are preserved.

Another normal paragraph.
----

[.result]
====
A normal paragraph.

 A sequence of lines that begin with at least one space is a literal paragraph.
 Literal paragraphs are treated as preformatted text.
 The text is shown in a fixed-width font
 and endlines are preserved.

Another normal paragraph.
====

.Admonition
----
NOTE: An admonition paragraph draws the reader's attention to
auxiliary information.
Its purpose is determined by the label
at the beginning of the paragraph.

Here are the other built-in admonition types:

TIP: Pro tip...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...
----

[.result]
====
NOTE: An admonition paragraph draws the reader's attention to
auxiliary information.
Its purpose is determined by the label
at the beginning of the paragraph.

Here are the other built-in admonition types:

TIP: Pro tip...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...
====

NOTE: You can also create <<admon-bl,admonition blocks>>.

.Lead paragraph
----
[.lead]
This text will be styled as a lead paragraph (i.e., larger font).
----

[.result]
====
[.lead]
This text will be styled as a lead paragraph (i.e., larger font).
====

NOTE: The default Asciidoctor stylesheet automatically styles the first paragraph of the preamble as a lead paragraph.

.More Paragraph, Admonition and Literal Block Examples
****
See these sections in the Asciidoctor User Manual for more information and examples.

* {para-ref}[Paragraphs]
* {literal-ref}[Literal Text and Blocks]
* {admon-ref}[Admonitions]
****

== Formatted Text

.Bold, Italic, and Monospace
----
_italic phrase_

__i__talic le__tt__ers

*bold phrase*

**b**old le**tt**ers

*_bold italic phrase_*

**__b__**old italic le**__tt__**ers

+monospace phrase+ and le++tt++ers

+_monospace italic phrase_+ and le++__tt__++ers

+*monospace bold phrase*+ and le++**tt**++ers

+*_monospace bold italic phrase_*+ and le++**__tt__**++ers

`inline literal passthrough` (monospace text without substitutions)
----

[.result]
====
_italic phrase_

__i__talic le__tt__ers

*bold phrase*

**b**old le**tt**ers

*_bold italic phrase_*

**__b__**old italic le**__tt__**ers

+monospace phrase+ and le++tt++ers

+_monospace italic phrase_+ and le++__tt__++ers

+*monospace bold phrase*+ and le++**tt**++ers

+*_monospace bold italic phrase_*+ and le++**__tt__**++ers

`inline literal passthrough` (monospace text without substitutions)
====

.Custom Styling
----
Do werewolves believe in [small]#small print#?

[big]##O##nce upon an infinite loop.
----

[.result]
====
Do werewolves believe in [small]#small print#?

[big]##O##nce upon an infinite loop.
====

.Superscript and Subscript
----
^super^script phrase

~sub~script phrase
----

[.result]
====
^super^script phrase

~sub~script phrase
====

.Curved Quotes
----
`single smart quotes'

``double smart quotes''
----

[.result]
====
`single smart quotes'

``double smart quotes''
====

.More Text Formatting Examples
****
See these sections in the Asciidoctor User Manual for more information and examples.

* {bold-ref}[Bold and Italic Formatting]
* {quote-ref}[Quotation Marks and Apostrophes]
* {sub-ref}[Subscript and Superscript]
* {mono-ref}[Monospace Formatting]
* {css-ref}[Custom Styling with Attributes]
* {pass-ref}[Passthrough Macros]
****

== Document Header

IMPORTANT: A header is optional.
When you do add a header to your document, the only required element is a title.

CAUTION: The header may not contain blank lines and must be offset from the content by at least one blank line.

.Title only
----
= My Document's Title

My document provides...
----

.Title and author line
----
= My Document's Title
Doc Writer <doc.writer@asciidoctor.org>

My document provides...
----

.Title, author line and revision line
----
= My Document's Title
Doc Writer <doc.writer@asciidoctor.org>
v1.0, 2014-01-01

My document provides...
----

IMPORTANT: You cannot have a revision line without an author line.

.Document header with attributes
----
= My Document's Title
Doc Writer <doc.writer@asciidoctor.org>
v1.0, 2014-01-01
:toc:
:imagesdir: assets/images
:homepage: http://asciidoctor.org

My document provides...
----

[[section-titles]]
== Section Titles (Headers)

.Article doctype
----
= Document Title (Level 0)

== Level 1 Section

=== Level 2 Section

==== Level 3 Section

===== Level 4 Section

====== Level 5 Section

== Another Level 1 Section
----

[.result]
====
// float is required to create plain headers
[float]
= Document Title (Level 0)

[float]
== Section Level 1

[float]
=== Section Level 2

[float]
==== Section Level 3

[float]
===== Section Level 4

[float]
====== Section Level 5
====

WARNING: When using the article doctype (the default), you can only have one level-0 section title (i.e., the document title) and it must be in the document header.

NOTE: The number of equal signs matches the heading level in the HTML output.
For example, _Section Level 1_ becomes an +<h2>+ heading.

.Book doctype
----
= Document Title (Level 0)

== Section Level 1

=== Section Level 2

==== Section Level 3

===== Section Level 4

====== Section Level 5

= Section Level 0
----

[.result]
====
// float is required to create plain headers
[float]
= Document Title (Level 0)

[float]
== Section Level 1

[float]
=== Section Level 2

[float]
==== Section Level 3

[float]
===== Section Level 4

[float]
====== Section Level 5

[float]
= Section Level 0
====

////
IMPORTANT: There are two other ways to define a section title.
_Their omission is intentional_.
They both require more markup and are therefore unnecessary.
The http://en.wikipedia.org/wiki/Setext[setext] title syntax (underlined text) is especially wasteful, hard to remember, hard to maintain and error prone.
The reader never sees the extra markup, so why type it?
*Be frugal!*
////

.Explicit id
----
[[primitives-nulls]]
== Primitive types and null values
----

.Section anchors and links (Asciidoctor only)

+sectanchors+::
When this document attribute is set, a section icon anchor appears in front of the section title.

+sectlinks+::
When this document attribute is set, the section titles become links.

NOTE: Section title anchors depend on the default Asciidoctor stylesheet to render properly.

== Include Files

.Document parts
----
= Reference Documentation
Lead Developer

This is documentation for project X.

\\include::basics.adoc[]

\\include::installation.adoc[]

\\include::example.adoc[]
----

CAUTION: Asciidoctor does not insert blank lines between adjacent include statements to keep the content separated.
Be sure to add a blank line in the source document to avoid unexpected results, such as a section title being swallowed.

.Include content from a URI
----
:asciidoctor-source: https://raw.github.com/asciidoctor/asciidoctor/master

\\include::{asciidoctor-source}/README.adoc[]
----

NOTE: Including content from a URI is potentially dangerous, so it's disabled if the safe mode is SECURE or greater.
Assuming the safe mode is less than SECURE, you must also set the +allow-uri-read+ attribute to permit Asciidoctor to read content from a URI.

== Horizontal Rules and Page Breaks

.Horizontal rule
----
'''
----

[.result]
====
'''
====

.Page break
----
<<<
----

== Lists

.Unordered, basic
----
* Edgar Allen Poe
* Sheri S. Tepper
* Bill Bryson

//^

* Kevin Spacey
* Jeremy Piven
----

[.result]
====
* Edgar Allen Poe
* Sheri S. Tepper
* Bill Bryson

//^

* Kevin Spacey
* Jeremy Piven
====

NOTE: Blank lines are required before and after a list.

TIP: You can force two lists apart with a line comment, as the previous example demonstrates.
The text in the comment, (`^`), is optional, but serves as a hint to other authors that this line serves as an "end of list" marker.

.Unordered, max nesting
----
* level 1
** level 2
*** level 3
**** level 4
***** level 5
* level 1
----

[.result]
====
* level 1
** level 2
*** level 3
**** level 4
***** level 5
* level 1
====

TIP: The unordered list marker can be changed using {list-marker}[block styles].

.Checklist
----
- [*] checked
- [x] also checked
- [ ] not checked
-     normal list item
----

[.result]
====
- [*] checked
- [x] also checked
- [ ] not checked
-     normal list item
====

TIP: Checklists can use {checklist-ref}[font-based icons and be interactive].

.Ordered, basic
----
. Step 1
. Step 2
. Step 3
----

[.result]
====
. Step 1
. Step 2
. Step 3
====

.Ordered, nested
----
. Step 1
. Step 2
.. Step 2a
.. Step 2b
. Step 3
----

[.result]
====
. Step 1
. Step 2
.. Step 2a
.. Step 2b
. Step 3
====

.Ordered, max nesting
----
. level 1
.. level 2
... level 3
.... level 4
..... level 5
. level 1
----

[.result]
====
. level 1
.. level 2
... level 3
.... level 4
..... level 5
. level 1
====

TIP: For ordered lists, Asciidoctor supports {list-number}[numeration styles] such as +lowergreek+ and +decimal-leading-zero+.

.Labeled, single-line
----
first term:: definition of first term
section term:: definition of second term
----

[.result]
====
first term:: definition of first term
section term:: definition of second term
====

.Labeled, multi-line
----
first term::
definition of first term
section term::
definition of second term
----

[.result]
====
first term::
definition of first term
section term::
definition of second term
====

.Q&A
----
[qanda]
What is Asciidoctor?::
  An implementation of the AsciiDoc processor in Ruby.
What is the answer to the Ultimate Question?:: 42
----

[.result]
====
[qanda]
What is Asciidoctor?::
  An implementation of the AsciiDoc processor in Ruby.
What is the answer to the Ultimate Question?:: 42
====

.Mixed
----
Operating Systems::
  Linux:::
    . Fedora
      * Desktop
    . Ubuntu
      * Desktop
      * Server
  BSD:::
    . FreeBSD
    . NetBSD

Cloud Providers::
  PaaS:::
    . OpenShift
    . CloudBees
  IaaS:::
    . Amazon EC2
    . Rackspace
----

[.result]
====
Operating Systems::
  Linux:::
    . Fedora
      * Desktop
    . Ubuntu
      * Desktop
      * Server
  BSD:::
    . FreeBSD
    . NetBSD

Cloud Providers::
  PaaS:::
    . OpenShift
    . CloudBees
  IaaS:::
    . Amazon EC2
    . Rackspace
====

TIP: Lists can be indented.
Leading whitespace is not significant.

.Complex content in outline lists
----
* Every list item has at least one paragraph of content,
  which may be wrapped, even using a hanging indent.
+
Additional paragraphs or blocks are adjoined by putting
a list continuation on a line adjacent to both blocks.
+
list continuation:: a plus sign (+) on a line by itself

* A literal paragraph does not require a list continuation.

 $ gem install asciidoctor

* AsciiDoc lists may contain any complex content.
+
[cols="2", options="header"]
|===
|Application
|Language

|AsciiDoc
|Python

|Asciidoctor
|Ruby
|===
----

[.result]
====
* Every list item has at least one paragraph of content,
  which may be wrapped, even using a hanging indent.
+
Additional paragraphs or blocks are adjoined by putting
a list continuation on a line adjacent to both blocks.
+
list continuation:: a plus sign (+) on a line by itself

* A literal paragraph does not require a list continuation.

 $ gem install asciidoctor

* AsciiDoc lists may contain any complex content.
+
[cols="2", options="header"]
|===
|Application
|Language

|AsciiDoc
|Python

|Asciidoctor
|Ruby
|===
====

== Links

.External
----
http://asciidoctor.org - automatic!

http://asciidoctor.org[Asciidoctor]

https://github.com/asciidoctor[Asciidoctor @ *GitHub*]
----

[.result]
====
http://asciidoctor.org - automatic!

http://asciidoctor.org[Asciidoctor]

https://github.com/asciidoctor[Asciidoctor @ *GitHub*]
====

.Relative
----
link:index.html[Docs]
----

[.result]
====
link:index.html[Docs]
====

.Email and IRC
----
devel@discuss.arquillian.org

mailto:devel@discuss.arquillian.org[Discuss Arquillian]

mailto:devel-join@discuss.arquillian.org[Subscribe, Subscribe me, I want to join!]

irc://irc.freenode.org/#asciidoctor
----

[.result]
====
devel@discuss.arquillian.org

mailto:devel@discuss.arquillian.org[Discuss Arquillian]

mailto:devel-join@discuss.arquillian.org[Subscribe, Subscribe me, I want to join!]

irc://irc.freenode.org/#asciidoctor
====

.Link with attributes (Asciidoctor only)
----
http://discuss.asciidoctor.org[Discuss Asciidoctor, role="external", window="_blank"]

http://discuss.asciidoctor.org[Discuss Asciidoctor^]

http://search.example.com["Google, Yahoo, Bing^", role="teal"]
----

[.result]
====
http://discuss.asciidoctor.org[Discuss Asciidoctor, role="external", window="_blank"]

http://discuss.asciidoctor.org[Discuss Asciidoctor^]

http://search.example.com["Google, Yahoo, Bing^", role="teal"]
====

NOTE: Links with attributes (including the subject and body segments on mailto links) are a feature unique to Asciidoctor.
To enable them, you must set the +linkattrs+ attribute on the document.
When they are enabled, you must quote the link text if it contains a comma.

.Inline anchors
----
[[bookmark-a]]Inline anchors make arbitrary content referenceable.

anchor:bookmark-b[]Use a cross reference to link to this location.
----

[.result]
====
[[bookmark-a]]Inline anchors make arbitrary content referenceable.

anchor:bookmark-b[]Use a cross reference to link to this location.
====

.Internal cross references
----
See <<paragraphs>> to learn how to write paragraphs.

Learn how to organize the document into <<section-titles,sections>>.
----

[.result]
====
See <<paragraphs>> to learn how to write paragraphs.

Learn how to organize the document into <<section-titles,sections>>.
====

.Inter-document cross references (Asciidoctor only)
----
Refer to <<document-b.adoc#section-b,Section B>> for more information.

See you when you get back from <<document-b#section-b,Section B>>!
----

== Images

.Block
----
image::sunset.jpg[]

image::sunset.jpg[Sunset]

[[img-sunset]]
.A mountain sunset
image::sunset.jpg[Sunset, 300, 200, link="http://www.flickr.com/photos/javh/5448336655"]

image::http://asciidoctor.org/images/octocat.jpg[GitHub mascot]
----

[.result]
====
image::sunset.jpg[]

image::sunset.jpg[Sunset]

[[img-sunset]]
.A mountain sunset
image::sunset.jpg[Sunset, 300, 200, link="http://www.flickr.com/photos/javh/5448336655"]

image::http://asciidoctor.org/images/octocat.jpg[GitHub mascot]
====

IMPORTANT: Images are resolved relative to the value of the {imagesdir-ref}[+imagesdir+ document attribute], which defaults to an empty value.
The +imagesdir+ attribute can be an absolute path, relative path or base URL.
If the image target is a URL or absolute path, the +imagesdir+ prefix is _not_ added.

TIP: You should use the +imagesdir+ attribute to avoid hard coding the shared path to your images in every image macro.

.Image macro using positioning role
----
image:sunset.jpg[Sunset,150,150,role="right"] What a beautiful sunset!
----

[.result]
====
image:sunset.jpg[Sunset,150,150,role="right"] What a beautiful sunset!
====

TIP: There are a variety of attributes available to {image-attributes}[position and frame images].

.Inline
----
Click image:icons/play.png[Play, title="Play"] to get the party started.

Click image:icons/pause.png[title="Pause"] when you need a break.
----

[.result]
====
Click image:icons/play.png[Play, title="Play"] to get the party started.

Click image:icons/pause.png[title="Pause"] when you need a break.
====

.Embedded
----
= Document Title
:data-uri:
----

NOTE: When the +data-uri+ attribute is set, all images in the document--including admonition icons--are embedded into the document as https://developer.mozilla.org/en-US/docs/data_URIs[data URIs].

TIP: Instead of declaring the +data-uri+ attribute in the document, you can pass it as a command-line argument using +-a data-uri+.

== Videos

.Block
----
video::video_file.mp4[]

video::video_file.mp4[width=640, start=60, options=autoplay]
----

.Embedded Youtube video
----
video::rPQoq7ThGAU[youtube]
----

.Embedded Vimeo video
----
video::67480300[vimeo]
----

TIP: You can control the video settings using {video-ref}[additional attributes and options] on the macro.

== Source Code

.Inline
----
Reference code like +types+ or +methods+ inline.
----

[.result]
====
Reference code like +types+ or +methods+ inline.
====

.Literal line
----
 Indent the line one space to insert a code snippet
----

[.result]
====
 Indent the line one space to insert a code snippet
====

.Literal block
----
....
error: The requested operation returned error: 1954 Forbidden search for defensive operations manual
absolutely fatal: operation initiation lost in the dodecahedron of doom
would you like to die again? y/n
....
----

[.result]
====
....
error: The requested operation returned error: 1954 Forbidden search for defensive operations manual
absolutely fatal: operation initiation lost in the dodecahedron of doom
would you like to die again? y/n
....
====

[listing]
.Listing block with title, no syntax highlighting
....
.Gemfile.lock
----
GEM
  remote: https://rubygems.org/
  specs:
    asciidoctor (0.1.4)

PLATFORMS
  ruby

DEPENDENCIES
  asciidoctor (~> 0.1.4)
----
....

[.result]
====
.Gemfile.lock
----
GEM
  remote: https://rubygems.org/
  specs:
    asciidoctor (0.1.4)

PLATFORMS
  ruby

DEPENDENCIES
  asciidoctor (~> 0.1.4)
----
====

[listing]
.Code block with title and syntax highlighting
....
[source,ruby]
.app.rb
----
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----
....

[.result]
====
[source,ruby]
.app.rb
----
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----
====

[listing, subs="specialcharacters"]
.Code block with callouts
....
[source,ruby]
----
require 'sinatra' <1>

get '/hi' do      <2>
  "Hello World!"  <3>
end
----
<1> Library import
<2> URL mapping
<3> Content for response
....

[.result]
====
[source,ruby]
----
require 'sinatra' <1>

get '/hi' do      <2>
  "Hello World!"  <3>
end
----
<1> Library import
<2> URL mapping
<3> Content for response
====

[listing, subs="specialcharacters"]
.Code block with non-selectable callouts
....
----
line of code  // <1>
line of code  # <2>
line of code  ;; <3>
----
<1> A callout behind a line comment for C-style languages.
<2> A callout behind a line comment for Ruby, Python, Perl, etc.
<3> A callout behind a line comment for Clojure.
....

[.result]
====
----
line of code  // <1>
line of code  # <2>
line of code  ;; <3>
----
<1> A callout behind a line comment for C-style languages.
<2> A callout behind a line comment for Ruby, Python, Perl, etc.
<3> A callout behind a line comment for Clojure.
====

[listing, subs="specialcharacters"]
.XML code block with a non-selectable callout
....
[source,xml]
----
<section>
  <title>Section Title</title> <!--1-->
</section>
----
<1> The section title is required.
....

[.result]
====
[source,xml]
----
<section>
  <title>Section Title</title> <!--1-->
</section>
----
<1> The section title is required.
====

[listing]
.Code block sourced from file
....
[source,ruby]
----
\\include::app.rb[]
----
....

[listing]
.Code block sourced from file relative to source directory
....
:sourcedir: src/main/java

[source,java]
----
\\include::{sourcedir}/org/asciidoctor/Asciidoctor.java[]
----
....

[listing]
.Strip leading indentation from source
....
[source,ruby,indent=0]
----
\\include::lib/document.rb[lines=5..10]
----
....

[NOTE]
====
* When +indent+ is 0, the leading block indent is stripped (tabs are replaced with 4 spaces).
* When +indent+ is > 0, the leading block indent is first stripped (tabs are replaced with 4 spaces), then a block is indented by the number of columns equal to this value.
====

.Code block without delimiters (no blank lines)
----
[source,xml]
<meta name="viewport"
  content="width=device-width, initial-scale=1.0">
----

[.result]
====
[source,xml]
<meta name="viewport"
  content="width=device-width, initial-scale=1.0">
====

[IMPORTANT]
.Enabling the syntax highlighter
====
Syntax highlighting is enabled by setting the +source-highlighter+ attribute in the document header or passed as an argument.

 :source-highlighter: pygments

The valid options for are +coderay+, +highlightjs+, +prettify+, and +pygments+.
====

== More Delimited Blocks

.Sidebar
----
.AsciiDoc history
****
AsciiDoc was first released in Nov 2002 by Stuart Rackham.
It was designed from the start to be a shorthand syntax
for producing professional documents like DocBook and LaTeX.
****
----

[.result]
====
.AsciiDoc history
****
AsciiDoc was first released in Nov 2002 by Stuart Rackham.
It was designed from the start to be a shorthand syntax
for producing professional documents like DocBook and LaTeX.
****
====

NOTE: Any block can have a title, positioned above the block.
A block title is a line of text that starts with a dot.
The dot cannot be followed by a space.

.Example
----
.Sample document
====
Here's a sample AsciiDoc document:

[listing]
....
= Title of Document
Doc Writer
:toc:

This guide provides...
....

The document header is useful, but not required.
====
----

[example.result]
--
.Sample document
====
Here's a sample AsciiDoc document:

[listing]
....
= Title of Document
Doc Writer
:toc:

This guide provides...
....

The document header is useful, but not required.
====
--

[[admon-bl]]
.Admonition
----
[NOTE]
====
An admonition block may contain complex content.

.A list
- one
- two
- three

Another paragraph.
====
----

[.result]
=====
[NOTE]
====
An admonition block may contain complex content.

.A list
- one
- two
- three

Another paragraph.
====
=====

[TIP]
.Admonition and callout icons
====
Asciidoctor can "draw" icons using {fontawesome-ref}[Font Awesome^] and CSS.

To use this feature, set the value of the +icons+ document attribute to +font+.
Asciidoctor will then emit HTML markup that selects an appropriate font character from the Font Awesome font for each admonition block.

Icons can also be used {icon-inline}[inline] and {icon-attribute}[styled].
====

.Blockquote
----
[quote, Abraham Lincoln, Soldiers' National Cemetery Dedication]
____
Four score and seven years ago our fathers brought forth
on this continent a new nation...
____

[quote, Albert Einstein]
A person who never made a mistake never tried anything new.

____
A person who never made a mistake never tried anything new.
____
----

[.result]
====
[quote, Abraham Lincoln, Soldiers' National Cemetery Dedication]
____
Four score and seven years ago our fathers brought forth
on this continent a new nation...
____

[quote, Albert Einstein]
A person who never made a mistake never tried anything new.

____
A person who never made a mistake never tried anything new.
____
====

.Abbreviated blockquote (Asciidoctor only)
----
"I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical."
-- Thomas Jefferson, Papers of Thomas Jefferson: Volume 11
----

[.result]
====
"I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical."
-- Thomas Jefferson, Papers of Thomas Jefferson: Volume 11
====

.Air quotes (Asciidoctor only)

As a tip of the hat to Dick, Asciidoctor recognizes text between "air quotes" as a quote block.
Air quotes are the best thing since fenced code blocks.

----
[, Richard M. Nixon]
""
When the President does it, that means that it's not illegal.
""
----

[.result]
====
[, Richard M. Nixon]
""
When the President does it, that means that it's not illegal.
""
====

.Passthrough
----
++++
<p>
Content in a passthrough block is passed to the output unprocessed.
That means you can include raw HTML, like this embedded Gist:
</p>

<script src="http://gist.github.com/mojavelinux/5333524.js">
</script>
++++
----

[.result]
====
++++
<p>
Content in a passthrough block is passed to the output unprocessed.
That means you can include raw HTML, like this embedded Gist:
</p>

<script src="http://gist.github.com/mojavelinux/5333524.js">
</script>
++++
====

.Open
----
--
An open block can be an anonymous container,
or it can masquerade as any other block.
--

[source]
--
puts "I'm a source block!"
--
----

[.result]
====
--
An open block can be an anonymous container,
or it can masquerade as any other block.
--

[source]
--
puts "I'm a source block!"
--
====

[listing]
.Custom substitutions
....
:version: 0.1.4

[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.asciidoctor</groupId>
  <artifactId>asciidoctor-java-integration</artifactId>
  <version>{version}</version>
</dependency>
----
....

[.result]
====
// the attribute value is hard-coded in this result since the example depends
// on a hypothetical document attribute
[source,xml]
----
<dependency>
  <groupId>org.asciidoctor</groupId>
  <artifactId>asciidoctor-java-integration</artifactId>
  <version>0.1.4</version>
</dependency>
----
====

== Block Id, Role and Options

.Traditional markup method for assigning block +id+ and +role+
----
[[goals]]
[role="incremental"]
* Goal 1
* Goal 2
----

.Shorthand markup method for assigning block +id+ and +role+ (Asciidoctor only)
----
[#goals.incremental]
* Goal 1
* Goal 2
----

[TIP]
====
* To specify multiple roles using the shorthand syntax, separate them by dots.
* The order of +id+ and +role+ values in the shorthand syntax does not matter.
====

.Traditional markup method for assigning quoted text anchor (+id+) and +role+
----
[[free_the_world]][big goal]_free the world_
----

.Shorthand markup method for assigning quoted text anchor (+id+) and +role+ (Asciidoctor only)
----
[#free_the_world.big.goal]_free the world_
----

.Role assigned to text enclosed in backticks
----
[rolename]`escaped monospace text`
----

.Traditional markup method for assigning block +options+
----
[options="header,footer,autowidth"]
|===
|Cell A |Cell B
|===
----

.Shorthand markup method for assigning block +options+ (Asciidoctor only)
----
[%header%footer%autowidth]
|===
|Cell A |Cell B
|===
----

== Comments

.Line
----
// A single-line comment.
----

TIP: Single-line comments can be used to divide elements, such as two adjacent lists.

.Block
----
////
A multi-line comment.

Notice it's a delimited block.
////
----

== Tables

.Table with a title, three columns, a header, and two rows of content
----
.Table Title
|===
|Name of Column 1 |Name of Column 2 |Name of Column 3 <1>
<2>
|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===
----
<1> Unless the +cols+ attribute is specified, the number of columns is equal to the number of vertical bars on the first non-blank line inside the block delimiters.
<2> When a blank line follows a single line of column titles, the column titles row will be styled as a header row by default.

[.result]
====
.Table Title
|===
|Name of Column 1 |Name of Column 2 |Name of Column 3

|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===
====

.Table with two columns, a header, and two rows of content
----
[cols="2*", options="header"] <1>
|===
|Name of Column 1
|Name of Column 2

|Cell in column 1, row 1
|Cell in column 2, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|===
----
<1> The +*+ in the +cols+ attribute is the repeat operator. It means repeat the column specification for the remainder of columns. In this case, it means to repeat the default formatting across 4 columns. When the header row is not defined on a single line, you must use the +cols+ attribute to set the number of columns and +options+ attributes to make the first row a header.

[.result]
====
[cols="2*", options="header"]
|===
|Name of Column 1
|Name of Column 2

|Cell in column 1, row 1
|Cell in column 2, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|===
====

.Table with three columns, a header, and two rows of content
----
[cols="1,1,2", options="header"] <1>
.Applications
|===
|Name
|Category
|Description

|Firefox
|Browser
|Mozilla Firefox is an open-source web browser.
It's designed for standards compliance,
performance, portability.

|Arquillian
|Testing
|An innovative and highly extensible testing platform.
Empowers developers to easily create real, automated tests.
|===
----
<1> In this example, the +cols+ attribute has two functions. It specifies that this table has three columns, and it sets their relative widths.

[.result]
====
[cols="1,1,2", options="header"]
.Applications
|===
|Name
|Category
|Description

|Firefox
|Browser
|Mozilla Firefox is an open-source web browser.
It's designed for standards compliance,
performance, portability.

|Arquillian
|Testing
|An innovative and highly extensible testing platform.
Empowers developers to easily create real, automated tests.
|===
====

.Table with column containing AsciiDoc content
----
[cols="2,2,5a"]
|===
|Firefox
|Browser
|Mozilla Firefox is an open-source web browser.

It's designed for:

* standards compliance
* performance
* portability

http://getfirefox.com[Get Firefox]!
|===
----

[.result]
====
[cols="2,2,5a"]
|===
|Firefox
|Browser
|Mozilla Firefox is an open-source web browser.

It's designed for:

* standards compliance
* performance
* portability

http://getfirefox.com[Get Firefox]!
|===
====

.Table from CSV data
----
[format="csv", options="header"]
|===
Artist,Track,Genre
Baauer,Harlem Shake,Hip Hop
The Lumineers,Ho Hey,Folk Rock
|===
----

[.result]
====
[format="csv", options="header"]
|===
Artist,Track,Genre
Baauer,Harlem Shake,Hip Hop
The Lumineers,Ho Hey,Folk Rock
|===
====

.Table from CSV data using shorthand (Asciidoctor only)
----
,===
Artist,Track,Genre

Baauer,Harlem Shake,Hip Hop
,===
----

[.result]
====
,===
Artist,Track,Genre

Baauer,Harlem Shake,Hip Hop
,===
====

.Table from CSV data in file
----
,===
\\include::customers.csv[]
,===
----

[.result]
====
,===
include::customers.csv[]
,===
====

.Table from DSV data using shorthand (Asciidoctor only)
----
:===
Artist:Track:Genre

Robyn:Indestructable:Dance
:===
----

[.result]
====
:===
Artist:Track:Genre

Robyn:Indestructable:Dance
:===
====

.Table with formatted, aligned and merged cells
----
[cols="e,m,^,>s", width="25%"]
|===
|1 >s|2 |3 |4
^|5 2.2+^.^|6 .3+<.>m|7
^|8
|9 2+>|10
|===
----

[.result]
====
[cols="e,m,^,>s", width="25%"]
|===
|1 >s|2 |3 |4
^|5 2.2+^.^|6 .3+<.>m|7
^|8
|9 2+>|10
|===
====

== UI Macros

IMPORTANT: You *must* set the +experimental+ attribute in the document header to enable these macros.

.Keyboard shortcuts (inline +kbd+ macro)
----
|===
|Shortcut |Purpose

|kbd:[F11]
|Toggle fullscreen

|kbd:[Ctrl+T]
|Open a new tab

|kbd:[Ctrl+Shift+N]
|New incognito window

|kbd:[Ctrl + +]
|Increase zoom
|===
----

[.result]
====
|===
|Shortcut |Purpose

|kbd:[F11]
|Toggle fullscreen

|kbd:[Ctrl+T]
|Open a new tab

|kbd:[Ctrl+Shift+N]
|New incognito window

|kbd:[Ctrl + +]
|Increase zoom
|===
====

.Menu selections (inline +menu+ macro)
----
To save the file, select menu:File[Save].

Select menu:View[Zoom > Reset] to reset the zoom level to the default setting.
----

[.result]
====
To save the file, select menu:File[Save].

Select menu:View[Zoom > Reset] to reset the zoom level to the default setting.
====

.Buttons (inline +btn+ macro)
----
Press the btn:[OK] button when you are finished.

Select a file in the file navigator and click btn:[Open].
----

[.result]
====
Press the btn:[OK] button when you are finished.

Select a file in the file navigator and click btn:[Open].
====

== Attributes and Substitutions

.Attribute declaration and usage
----
:homepage: http://asciidoctor.org
:docslink: http://asciidoctor.org/docs[Asciidoctor's Docs]
:desc: Asciidoctor is a mature, plain-text document format for +
       writing notes, articles, documentation, books, and more. +
       It's also a text processor & toolchain for translating +
       documents into various output formats (i.e., backends), +
       including HTML, DocBook, PDF and ePub.
:checkedbox: pass:normal[+[&#10004;]+]

Check out {homepage}[Asciidoctor]!

{desc}

Check out {docslink} too!

{checkedbox} That's done!
----

[.result]
====
// I have to use a nested doc hack here, otherwise the attributes won't resolve
[.unstyled]
|===
a|
:homepage: http://asciidoctor.org
:docslink: http://asciidoctor.org/docs[Asciidoctor's Docs]
:desc: Asciidoctor is a mature, plain-text document format for +
       writing notes, articles, documentation, books, and more. +
       It's also a text processor & toolchain for translating +
       documents into various output formats (i.e., backends), +
       including HTML, DocBook, PDF and ePub.
:checkedbox: pass:normal[+[&#10004;]+]

Check out {homepage}[Asciidoctor]!

{desc}

Check out {docslink} too!

{checkedbox} That's done!
|===
====

.Attribute assignment precedence (highest to lowest)
- Attribute passed to the API or CLI that does not end in +@+
- Attribute defined in the document
- Attribute passed to the API or CLI that ends in +@+
- Intrinsic attribute value (default values)

TIP: To make an attribute value that is passed to the API or CLI have a lower precedence than an assignment in the document, add an +@+ symbol to the end of the attribute value.

// Table of literal character attributes
.Built-in literal attributes
[width="70%", cols="^1l,^1l,^1"]
|===
|Attribute reference |Replacement |Rendered

|\\{lt}
|<
|<

|\\{gt}
|>
|>

|\\{amp}
|&
|&

|\\{startsb}
|[
|[

|\\{endsb}
|]
|]

|\\{vbar}
|\\|
|\\|

|\\{caret}
|^
|^

|\\{asterisk}
|*
|*

|\\{tilde}
|~
|~

|\\{apostrophe}
|'
|'

|\\{backslash}
|\\
|\\

|\\{backtick}
|`
|`

|\\{two-colons}
|::
|::

|\\{two-semicolons}
|;;
|;;

|===

// Table of character reference attributes
.Built-in entity attributes
[width="70%", cols="^1l,^1l,^1"]
|===
|Attribute reference |Replacement |Rendered

|\\{empty}
|_nothing_
|{empty}

|\\{sp}, \\{space}
|_single space_
|{sp}

|\\{nbsp}
|\\&#160;
|{nbsp}

|\\{zwsp}
|\\&#8203;
|{zwsp}

|\\{wj}
|\\&#8288;
|{wj}

|\\{apos}
|\\&#39;
|{apos}

|\\{quot}
|\\&#34;
|{quot}

|\\{lsquo}
|\\&#8216;
|{lsquo}

|\\{rsquo}
|\\&#8217;
|{rsquo}

|\\{ldquo}
|\\&#8220;
|{ldquo}

|\\{rdquo}
|\\&#8221;
|{rdquo}

|\\{deg}
|\\&#176;
|{deg}

|\\{plus}
|\\&#43;
|{plus}

|\\{brvbar}
|\\&#166;
|{brvbar}
|===

// Table of built-in data attributes
.Built-in data attributes
[width="70%",cols="1m,3"]
|===
|Attribute |Description

|asciidoctor
|Calls the processor

|asciidoctor-version
|Version of the processor

|backend
|Backend used to render document

|docdate
|Last modified date

|docdatetime
|Last modified date and time

|docdir
|Name of document directory

|docfile
|Name of document file

|doctime
|Last modified time

|doctitle
|The title of the document

|doctype
|Document's doctype (e.g., article)

|localdate
|Local date when rendered

|localdatetime
|Local date and time when rendered

|localtime
|Local time when rendered
|===

.Named substitutions
[horizontal]
+none+:: Disables substitutions

+normal+:: Performs all substitutions except for callouts

+verbatim+:: Replaces special characters and processes callouts

+specialcharacters+:: Replaces +<+, +>+, and +&+ with their corresponding entities

+quotes+:: Applies text formatting

+attributes+:: Replaces attribute references

+replacements+:: Substitutes textual and character reference replacements

+macros+:: Processes macros

+post_replacements+:: Replaces the line break character (+{plus}+)

.Counter attributes
----
[caption=""]
.Parts{counter2:index:0}
|===
|Part Id |Description

|PX-{counter:index}
|Description of PX-{index}

|PX-{counter:index}
|Description of PX-{index}
|===
----

[.result]
====
[caption=""]
.Parts{counter2:index:0}
|===
|Part Id |Description

|PX-{counter:index}
|Description of PX-{index}

|PX-{counter:index}
|Description of PX-{index}
|===
====

==  Text Replacement

// Table of text replacements performed during replacements substitution
////
Included in:

- user-manual: Text Substitutions: Replacements
- quick-ref
////

[cols="2,^1l,^1l,^1,2"]
.Textual symbol replacements
|===
|Name |Syntax |Unicode Replacement |Rendered |Notes

|Copyright
|\\(C)
|\\&#169;
|(C)
|

|Registered
|\\(R)
|\\&#174;
|(R)
|

|Trademark
|\\(TM)
|\\&#8482;
|(TM)
|

|Em dash
|\\--
|\\&#8212;
|{empty}--{empty}
|When space is detected on either side of the em dash, the thin space numeric character entity (+\\&#8201;+) is also substituted into the document.

|ellipses
|\\...
|\\&#8230;
|...
|

|right single arrow
|\\->
|\\&#8594;
|->
|

|right double arrow
|\\=>
|\\&#8658;
|=>
|

|left single arrow
|\\<-
|\\&#8592;
|<-
|

|left double arrow
|\\<=
|\\&#8656;
|<=
|

|apostrophe
|Sam\\'s
|Sam\\&#8217;s
|Sam's
|The vertical form apostrophe is replaced with the curved form apostrophe.
|===

TIP: Any named, numeric or hex http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references[XML entity reference] is supported.

== Escaping Text

.Backslash
----
\\*Stars* is not rendered as bold text.
The asterisks around the word are preserved.

\\{author} is not resolved to the author name.
The curly brackets around the word are preserved.

The backslash character is automatically removed.
----

[.result]
====
\\*Stars* is not rendered as bold text.
The asterisks around the word are preserved.

\\{author} is not resolved to the author name.
The curly brackets around the word are preserved.

The backslash character is automatically removed.
====

.Double dollar
----
$$*Stars*$$ is not rendered as bold text.
The asterisks around the word are preserved.

$$&amp;$$ renders as an XML entity instead of &.
----

[.result]
====
$$*Stars*$$ is not rendered as bold text.
The asterisks around the word are preserved.

$$&amp;$$ renders as an XML entity instead of &.
====

.Triple plus and inline passthrough macro
----
+++<u>underline me</u>+++ renders as underlined text.

pass:[<u>underline me</u>] also renders as underlined text.
----

[.result]
====
+++<u>underline me</u>+++ renders as underlined text.

pass:[<u>underline me</u>] also renders as underlined text.
====

.Backticks
----
`Text in {backticks}` renders exactly as entered, in `monospace`.
The attribute reference is not resolved.
----

[.result]
====
`Text in {backticks}` renders exactly as entered, in `monospace`.
The attribute reference is not resolved.
====

== Table of Contents (ToC)

.Document with ToC
----
= AsciiDoc Writer's Guide
Doc Writer <doc.writer@asciidoc.org>
v1.0, 2013-01-01
:toc:
----

.Document with ToC positioned on the right
----
= AsciiDoc Writer's Guide
Doc Writer <doc.writer@asciidoc.org>
v1.0, 2013-01-01
:toc: right
----

TIP: The ToC {toc-ref}["title, levels, and positioning"] can be customized.

== Bibliography

.References
----
'The Pragmatic Programmer' <<prag>> should be required reading for
all developers.

[bibliography]
- [[[prag]]] Andy Hunt & Dave Thomas. 'The Pragmatic Programmer:
  From Journeyman to Master'. Addison-Wesley. 1999.
- [[[seam]]] Dan Allen. 'Seam in Action'. Manning Publications.
  2008.
----

[.result]
====
'The Pragmatic Programmer' <<prag>> should be required reading for
all developers.

[bibliography]
- [[[prag]]] Andy Hunt & Dave Thomas. 'The Pragmatic Programmer:
  From Journeyman to Master'. Addison-Wesley. 1999.
- [[[seam]]] Dan Allen. 'Seam in Action'. Manning Publications.
  2008.
====

[[section-footnotes]]
== Footnotes

.Normal and reusable footnotes
----
A statement.footnote:[Clarification about this statement.]

A bold statement.footnoteref:[disclaimer,These opinions are my own.]

Another bold statement.footnoteref:[disclaimer]
----

[.result]
====
[.unstyled]
|===
a|
A statement.footnote:[Clarification about this statement.]

A bold statement.footnoteref:[disclaimer,These opinions are my own.]

Another bold statement.footnoteref:[disclaimer]
|===
====

== Markdown Compatibility

IMPORTANT: Markdown compatibility is only available by default in Asciidoctor.
You can configure AsciiDoc (Python) to recognize this syntax by putting https://github.com/asciidoctor/asciidoctor/blob/master/compat/asciidoc.conf[the AsciiDoc compatibility file] from Asciidoctor in the same directory as the document being processed.

.Markdown-style headings
----
# Document Title (Level 0)

## Section Level 1

### Section Level 2

#### Section Level 3

##### Section Level 4

###### Section Level 5
----

[.result]
====
[float]
# Document Title (Level 0)

[float]
## Section Level 1

[float]
### Section Level 2

[float]
#### Section Level 3

[float]
##### Section Level 4

[float]
###### Section Level 5
====

.Fenced code block with syntax highlighting
----
```ruby
require 'sinatra'

get '/hi' do
  "Hello World!"
end
```
----

[.result]
====
```ruby
require 'sinatra'

get '/hi' do
  "Hello World!"
end
```
====

.Markdown-style blockquote
----
> I hold it that a little rebellion now and then is a good thing,
> and as necessary in the political world as storms in the physical.
> -- Thomas Jefferson, Papers of Thomas Jefferson: Volume 11
----

[.result]
====
> I hold it that a little rebellion now and then is a good thing,
> and as necessary in the political world as storms in the physical.
> -- Thomas Jefferson, Papers of Thomas Jefferson: Volume 11
====

.Markdown-style blockquote with block content
----
> > What's new?
>
> I've got Markdown in my AsciiDoc!
>
> > Like what?
>
> * Blockquotes
> * Headings
> * Fenced code blocks
>
> > Is there more?
>
> Yep. AsciiDoc and Markdown share a lot of common syntax already.
----

[.result]
====
> > What's new?
>
> I've got Markdown in my AsciiDoc!
>
> > Like what?
>
> * Blockquotes
> * Headings
> * Fenced code blocks
>
> > Is there more?
>
> Yep. AsciiDoc and Markdown share a lot of common syntax already.
====

.Markdown-style horizontal rules
----
---

- - -

***

* * *
----

[.result]
====
---

- - -

***

* * *
====

== User Manual and Help

To learn more about Asciidoctor and its capabilities, check out the other {docref}[Asciidoctor guides] and its {user-ref}[User Manual].
Also, don't forget to join the {mailinglist}[Asciidoctor mailing list], where you can ask questions and leave comments.
EOS

require 'native'
$global.addEventListener 'DOMContentLoaded', proc {
  base_dir = File.dirname $global.window.location.href
  ENV['HOME'] = base_dir
  timings = Asciidoctor::Timings.new
  html = Asciidoctor.convert data, :safe => :safe, :attributes => %w(showtitle sectanchors imagesdir=./images), :timings => timings
  timings.print_report
  $global.document.getElementById('content').innerHTML = html
}, false
