= Extensions ecosystem
:uri-twemoji: https://blog.twitter.com/developer/en_us/a/2014/open-sourcing-twitter-emoji-for-everyone.html
:uri-plantuml-server: https://github.com/plantuml/plantuml-server
:uri-chartist: https://gionkunz.github.io/chartist-js/
:uri-kroki: https://kroki.io/

:uri-ext-interactive-runner-gh: https://github.com/oncletom/asciidoctor-extension-interactive-runner
:uri-ext-plantuml-gh: https://github.com/eshepelyuk/asciidoctor-plantuml.js
:uri-ext-emoji-gh: https://github.com/mogztter/asciidoctor-emoji
:uri-ext-chart-gh: https://github.com/mogztter/asciidoctor-chart
:uri-ext-kroki-gh: https://github.com/Mogztter/asciidoctor-kroki
:uri-ext-tweet-gh: https://github.com/Mogztter/asciidoctor-tweet

Here's a list of extensions provided by the awesome community:

Chart::
Render charts using {uri-chartist}[Chartist.js]. +
{uri-ext-chart-gh}

Diagrams::
Convert diagrams to images using {uri-kroki}[Kroki]. +
{uri-ext-kroki-gh}

Emoji::
Inline macro to render `emoji:heart[]` as an `<img>` that points to a remote SVG using {uri-twemoji}[Twemoji from Twitter]. +
{uri-ext-emoji-gh}

Interative runner::
Transform AsciiDoc code listings into interactive playgrounds which run in the browser.
Add the `%interactive` option to your `[source]` block. +
{uri-ext-interactive-runner-gh}

PlantUML::
Render PlantUML, Ditaa and Graphiz (DOT) diagrams as PNG or SVG using a {uri-plantuml-server}[PlantUML server]. +
{uri-ext-plantuml-gh}

Tweet::
Render tweet using the Twitter API.
Use the `tweet` macro with a tweet id: `tweet::1041369960436703232[]`. +
{uri-ext-tweet-gh}
