= Extensions ecosystem
:uri-twemoji: https://blog.twitter.com/developer/en_us/a/2014/open-sourcing-twitter-emoji-for-everyone.html
:uri-plantuml-server: https://github.com/plantuml/plantuml-server
:uri-chartist: https://gionkunz.github.io/chartist-js/
:uri-kroki: https://kroki.io/
:uri-bytefield: https://bytefield-svg.deepsymmetry.org/

:uri-ext-interactive-runner-gh: https://github.com/oncletom/asciidoctor-extension-interactive-runner
:uri-ext-plantuml-gh: https://github.com/eshepelyuk/asciidoctor-plantuml.js
:uri-ext-emoji-gh: https://github.com/mogztter/asciidoctor-emoji
:uri-ext-chart-gh: https://github.com/mogztter/asciidoctor-chart
:uri-ext-color-gh: https://github.com/mogztter/asciidoctor-color
:uri-ext-kroki-gh: https://github.com/mogztter/asciidoctor-kroki
:uri-ext-tweet-gh: https://github.com/mogztter/asciidoctor-tweet
:uri-ext-bytefield-gh: https://github.com/Deep-Symmetry/bytefield-svg
:uri-ext-antora-indexer-gl: https://gitlab.com/djencks/asciidoctor-antora-indexer
:uri-ext-jsonpath-gl: https://gitlab.com/djencks/asciidoctor-jsonpath
:uri-ext-mathjax-gl: https://gitlab.com/djencks/asciidoctor-mathjax.js
:uri-ext-openblock-gl: https://gitlab.com/djencks/asciidoctor-openblock
:uri-ext-template-gl: https://gitlab.com/djencks/asciidoctor-template
:uri-ext-highlight-gh: https://github.com/jirutka/asciidoctor-highlight.js

Here's a list of extensions provided by the awesome community:

Byte field::
Draw byte field diagrams using {uri-bytefield}[bytefield-svg]. +
{uri-ext-bytefield-gh}

Chart::
Render charts using {uri-chartist}[Chartist.js]. +
{uri-ext-chart-gh}

Color::
Render color chips for a given color reference (either a name, rgb, rgba, hsl, hsla or hex reference) +
{uri-ext-color-gh}

Diagrams::
Convert diagrams to images using {uri-kroki}[Kroki]. +
{uri-ext-kroki-gh}

Emoji::
Inline macro to render `emoji:heart[]` as an `<img>` that points to a remote SVG using {uri-twemoji}[Twemoji from Twitter]. +
{uri-ext-emoji-gh}

Highlight.js::
Highlighting source listing blocks using https://highlightjs.org[highlight.js] during document conversion (instead of in browser as the built-in highlight.js support). +
{uri-ext-highlight-gh}

Interactive runner::
Transform AsciiDoc code listings into interactive playgrounds which run in the browser.
Add the `%interactive` option to your `[source]` block. +
{uri-ext-interactive-runner-gh}

MathJax::
Server-side mathjax rendering into inline svg. +
{uri-ext-mathjax-gl}

Open Block::
Nest open blocks to any depth using a block macro, at least until the spec allows this directly. +
{uri-ext-openblock-gl}

PlantUML::
Render PlantUML, Ditaa and Graphiz (DOT) diagrams as PNG or SVG using a {uri-plantuml-server}[PlantUML server]. +
{uri-ext-plantuml-gh} +
No longer maintained.
Consider using Kroki instead.

Queries::
Query an external json document or (in Antora) the Antora content catalog and render the result as a list, table, count, or repeating template block.
Json:::
{uri-ext-jsonpath-gl}
Antora:::
{uri-ext-antora-indexer-gl}

Template::
Define a block or inline template and "call" it with "variables", with the result isolated from the main document:
that is, the attributes do not leak out of the template. +
{uri-ext-template-gl}

Tweet::
Render tweet using the Twitter API.
Use the `tweet` macro with a tweet id: `tweet::1041369960436703232[]`. +
{uri-ext-tweet-gh}
