export class DocBook5Converter extends ConverterBase {
    convert_document(node: any): Promise<string>;
    convert_embedded(node: any): Promise<string>;
    convert_section(node: any): Promise<string>;
    convert_admonition(node: any): Promise<string>;
    convert_audio(_node: any): Promise<string>;
    convert_colist(node: any): Promise<string>;
    convert_dlist(node: any): Promise<string>;
    convert_example(node: any): Promise<string>;
    convert_floating_title(node: any): Promise<string>;
    convert_image(node: any): Promise<string>;
    convert_listing(node: any): Promise<string>;
    convert_literal(node: any): Promise<string>;
    convert_pass(node: any): Promise<any>;
    convert_stem(node: any): Promise<string>;
    convert_olist(node: any): Promise<string>;
    convert_open(node: any): Promise<any>;
    convert_page_break(_node: any): Promise<string>;
    convert_paragraph(node: any): Promise<string>;
    convert_preamble(node: any): Promise<any>;
    convert_quote(node: any): Promise<string>;
    convert_thematic_break(_node: any): Promise<string>;
    convert_sidebar(node: any): Promise<string>;
    convert_table(node: any): Promise<string>;
    convert_toc(_node: any): Promise<string>;
    convert_ulist(node: any): Promise<string>;
    convert_verse(node: any): Promise<string>;
    convert_video(_node: any): Promise<string>;
    convert_inline_anchor(node: any): Promise<string>;
    convert_inline_break(node: any): Promise<string>;
    convert_inline_button(node: any): Promise<string>;
    convert_inline_callout(node: any): Promise<string>;
    convert_inline_footnote(node: any): Promise<string>;
    convert_inline_image(node: any): Promise<string>;
    convert_inline_indexterm(node: any): Promise<string>;
    convert_inline_kbd(node: any): Promise<string>;
    convert_inline_menu(node: any): Promise<string>;
    convert_inline_quoted(node: any): Promise<string>;
    _commonAttributes(id: any, role?: any, reftext?: any): string;
    _imageSizeAttributes(attributes: any): string;
    _authorTag(doc: any, author: any): string;
    _documentInfoTag(doc: any, abstract: any): Promise<string>;
    _findRootAbstract(doc: any): any;
    _extractAbstract(document: any, abstract: any): any;
    _restoreAbstract(abstract: any): void;
    _getRootDocument(node: any): any;
    _generateDocumentId(doc: any): string;
    _encloseContent(node: any): Promise<any>;
    _titleTag(node: any, optional?: boolean): string;
    _coverTag(doc: any, face: any, usePlaceholder?: boolean): Promise<string>;
    _blockquoteTag(node: any, tagName: any, contentFn: any): Promise<string>;
}
export default DocBook5Converter;
import { ConverterBase } from '../converter.js';
