name: Build core

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  activate:
    if: |
      (github.event_name == 'workflow_call') ||
      (github.event_name == 'schedule' && github.repository_owner == 'asciidoctor') ||
      (github.event_name != 'schedule' && !endsWith(github.event.head_commit.message, '[skip ci]'))
    runs-on: ubuntu-latest
    steps:
      - name: Proceed
        run: echo ok go
  build:
    needs: activate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Lint and build
        run: |
          npm run lint
          npm run build -w @asciidoctor/core
      - name: Check no uncommitted changes after build
        run: git diff --exit-code

  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install chromium
      - name: Test
        shell: bash
        run: |
          npm test

  native_images:
    needs: test
    uses: ./.github/workflows/native-image.yml

  docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository_owner == 'asciidoctor'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: |
          npm ci
      - name: Generate API documentation
        run: npm run docs -w @asciidoctor/core
      - name: Publish to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/core/build/docs
          target-folder: main
