name: Documentation notify

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify Netlify
        env:
          NETLIFY_WEBHOOK_URL: ${{ secrets.NETLIFY_WEBHOOK_URL }}
        run: ./scripts/notify.sh
